-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (17 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (17 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (17 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (17 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (17 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv10_1FF : STD_LOGIC_VECTOR (9 downto 0) := "0111111111";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal exp_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce0 : STD_LOGIC;
    signal exp_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce1 : STD_LOGIC;
    signal exp_table_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce2 : STD_LOGIC;
    signal exp_table_q2 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce3 : STD_LOGIC;
    signal exp_table_q3 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce4 : STD_LOGIC;
    signal exp_table_q4 : STD_LOGIC_VECTOR (17 downto 0);
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_ce0 : STD_LOGIC;
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal data_4_val_read_reg_769 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal data_3_val_read_reg_776 : STD_LOGIC_VECTOR (17 downto 0);
    signal data_2_val_read_reg_781 : STD_LOGIC_VECTOR (17 downto 0);
    signal data_1_val_read_reg_786 : STD_LOGIC_VECTOR (17 downto 0);
    signal data_0_val_read_reg_791 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln66_2_fu_208_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln66_2_reg_796 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln245_1_fu_469_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln245_1_reg_802 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln245_3_fu_495_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln245_3_reg_807 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_load_2_reg_837 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_load_2_reg_837_pp0_iter3_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_load_3_reg_843 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_load_3_reg_843_pp0_iter3_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_load_4_reg_849 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_load_4_reg_849_pp0_iter3_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_load_reg_855 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table_load_1_reg_860 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln255_2_fu_529_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln255_3_fu_560_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln255_4_fu_591_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln255_fu_596_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln255_1_fu_600_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln265_fu_635_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln66_fu_156_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln66_fu_156_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln66_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_fu_168_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln66_fu_168_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln66_1_fu_176_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln66_1_fu_176_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln66_1_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_1_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_1_fu_188_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln66_1_fu_188_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln66_fu_168_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln66_1_fu_188_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln66_2_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_2_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_3_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_3_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_max_fu_226_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln245_fu_232_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln245_1_fu_235_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln245_fu_239_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_5_fu_245_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_253_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln245_2_fu_279_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln245_1_fu_282_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_7_fu_288_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_296_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_2_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln245_3_fu_322_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln245_2_fu_325_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_9_fu_331_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_339_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_4_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln245_4_fu_365_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln245_3_fu_368_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_11_fu_374_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_382_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_6_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln245_5_fu_408_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln245_4_fu_411_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_13_fu_417_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_425_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_8_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln245_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_1_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln245_fu_451_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_459_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln245_1_fu_310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_3_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln245_2_fu_477_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_fu_485_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln245_2_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_5_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln245_4_fu_503_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_fu_511_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln245_5_fu_521_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln245_3_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_7_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln245_6_fu_534_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_fu_542_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln245_7_fu_552_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln245_4_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_9_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln245_8_fu_565_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_fu_573_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln245_9_fu_583_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln51_fu_604_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_fu_604_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_1_fu_610_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_2_fu_614_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_fu_604_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_sum_fu_619_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_s_fu_625_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln268_fu_647_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln268_fu_640_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln268_fu_647_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln268_1_fu_666_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln268_1_fu_666_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln268_2_fu_685_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln268_2_fu_685_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln268_3_fu_704_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln268_3_fu_704_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln268_4_fu_723_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln268_4_fu_723_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_18s_18s_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_exp_table_ROM_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_invert_table_Rcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_exp_table_ROM_bkb
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0,
        ce0 => exp_table_ce0,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1,
        q1 => exp_table_q1,
        address2 => exp_table_address2,
        ce2 => exp_table_ce2,
        q2 => exp_table_q2,
        address3 => exp_table_address3,
        ce3 => exp_table_ce3,
        q3 => exp_table_q3,
        address4 => exp_table_address4,
        ce4 => exp_table_ce4,
        q4 => exp_table_q4);

    invert_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_invert_table_Rcud
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0,
        q0 => invert_table_q0);

    mul_18s_18s_30_1_1_U385 : component myproject_mul_18s_18s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln268_fu_647_p0,
        din1 => exp_table_load_reg_855,
        dout => mul_ln268_fu_647_p2);

    mul_18s_18s_30_1_1_U386 : component myproject_mul_18s_18s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln268_1_fu_666_p0,
        din1 => exp_table_load_1_reg_860,
        dout => mul_ln268_1_fu_666_p2);

    mul_18s_18s_30_1_1_U387 : component myproject_mul_18s_18s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln268_2_fu_685_p0,
        din1 => exp_table_load_2_reg_837_pp0_iter3_reg,
        dout => mul_ln268_2_fu_685_p2);

    mul_18s_18s_30_1_1_U388 : component myproject_mul_18s_18s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln268_3_fu_704_p0,
        din1 => exp_table_load_3_reg_843_pp0_iter3_reg,
        dout => mul_ln268_3_fu_704_p2);

    mul_18s_18s_30_1_1_U389 : component myproject_mul_18s_18s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln268_4_fu_723_p0,
        din1 => exp_table_load_4_reg_849_pp0_iter3_reg,
        dout => mul_ln268_4_fu_723_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_0_val_read_reg_791 <= data_0_val;
                data_1_val_read_reg_786 <= data_1_val;
                data_2_val_read_reg_781 <= data_2_val;
                data_3_val_read_reg_776 <= data_3_val;
                data_4_val_read_reg_769 <= data_4_val;
                select_ln245_1_reg_802 <= select_ln245_1_fu_469_p3;
                select_ln245_3_reg_807 <= select_ln245_3_fu_495_p3;
                select_ln66_2_reg_796 <= select_ln66_2_fu_208_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce))) then
                exp_table_load_1_reg_860 <= exp_table_q0;
                exp_table_load_reg_855 <= exp_table_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce))) then
                exp_table_load_2_reg_837 <= exp_table_q4;
                exp_table_load_3_reg_843 <= exp_table_q3;
                exp_table_load_4_reg_849 <= exp_table_q2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then
                exp_table_load_2_reg_837_pp0_iter3_reg <= exp_table_load_2_reg_837;
                exp_table_load_3_reg_843_pp0_iter3_reg <= exp_table_load_3_reg_843;
                exp_table_load_4_reg_849_pp0_iter3_reg <= exp_table_load_4_reg_849;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln51_1_fu_610_p2 <= std_logic_vector(signed(exp_table_load_3_reg_843) + signed(exp_table_load_4_reg_849));
    add_ln51_2_fu_614_p2 <= std_logic_vector(unsigned(add_ln51_1_fu_610_p2) + unsigned(exp_table_load_2_reg_837));
    add_ln51_fu_604_p0 <= exp_table_q0;
    add_ln51_fu_604_p1 <= exp_table_q1;
    add_ln51_fu_604_p2 <= std_logic_vector(signed(add_ln51_fu_604_p0) + signed(add_ln51_fu_604_p1));
    and_ln245_1_fu_310_p2 <= (xor_ln245_2_fu_304_p2 and tmp_8_fu_296_p3);
    and_ln245_2_fu_353_p2 <= (xor_ln245_4_fu_347_p2 and tmp_10_fu_339_p3);
    and_ln245_3_fu_396_p2 <= (xor_ln245_6_fu_390_p2 and tmp_12_fu_382_p3);
    and_ln245_4_fu_439_p2 <= (xor_ln245_8_fu_433_p2 and tmp_14_fu_425_p3);
    and_ln245_fu_267_p2 <= (xor_ln245_fu_261_p2 and tmp_6_fu_253_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to3)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= mul_ln268_fu_647_p2(29 downto 14);
    ap_return_1 <= mul_ln268_1_fu_666_p2(29 downto 14);
    ap_return_2 <= mul_ln268_2_fu_685_p2(29 downto 14);
    ap_return_3 <= mul_ln268_3_fu_704_p2(29 downto 14);
    ap_return_4 <= mul_ln268_4_fu_723_p2(29 downto 14);
    exp_sum_fu_619_p2 <= std_logic_vector(unsigned(add_ln51_2_fu_614_p2) + unsigned(add_ln51_fu_604_p2));
    exp_table_address0 <= zext_ln255_1_fu_600_p1(10 - 1 downto 0);
    exp_table_address1 <= zext_ln255_fu_596_p1(10 - 1 downto 0);
    exp_table_address2 <= zext_ln255_4_fu_591_p1(10 - 1 downto 0);
    exp_table_address3 <= zext_ln255_3_fu_560_p1(10 - 1 downto 0);
    exp_table_address4 <= zext_ln255_2_fu_529_p1(10 - 1 downto 0);

    exp_table_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce))) then 
            exp_table_ce0 <= ap_const_logic_1;
        else 
            exp_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce))) then 
            exp_table_ce1 <= ap_const_logic_1;
        else 
            exp_table_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce2 <= ap_const_logic_1;
        else 
            exp_table_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce3 <= ap_const_logic_1;
        else 
            exp_table_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce4 <= ap_const_logic_1;
        else 
            exp_table_ce4 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln66_1_fu_176_p0 <= data_2_val;
    icmp_ln66_1_fu_176_p1 <= data_3_val;
    icmp_ln66_1_fu_176_p2 <= "1" when (signed(icmp_ln66_1_fu_176_p0) < signed(icmp_ln66_1_fu_176_p1)) else "0";
    icmp_ln66_2_fu_196_p2 <= "1" when (signed(select_ln66_fu_168_p3) < signed(select_ln66_1_fu_188_p3)) else "0";
    icmp_ln66_3_fu_216_p2 <= "1" when (signed(select_ln66_2_reg_796) < signed(data_4_val_read_reg_769)) else "0";
    icmp_ln66_fu_156_p0 <= data_0_val;
    icmp_ln66_fu_156_p1 <= data_1_val;
    icmp_ln66_fu_156_p2 <= "1" when (signed(icmp_ln66_fu_156_p0) < signed(icmp_ln66_fu_156_p1)) else "0";
    invert_table_address0 <= zext_ln265_fu_635_p1(10 - 1 downto 0);

    invert_table_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce))) then 
            invert_table_ce0 <= ap_const_logic_1;
        else 
            invert_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln268_1_fu_666_p0 <= sext_ln268_fu_640_p1(18 - 1 downto 0);
    mul_ln268_2_fu_685_p0 <= sext_ln268_fu_640_p1(18 - 1 downto 0);
    mul_ln268_3_fu_704_p0 <= sext_ln268_fu_640_p1(18 - 1 downto 0);
    mul_ln268_4_fu_723_p0 <= sext_ln268_fu_640_p1(18 - 1 downto 0);
    mul_ln268_fu_647_p0 <= sext_ln268_fu_640_p1(18 - 1 downto 0);
    select_ln245_1_fu_469_p3 <= 
        select_ln245_fu_451_p3 when (xor_ln245_1_fu_273_p2(0) = '1') else 
        tmp_fu_459_p4;
    select_ln245_2_fu_477_p3 <= 
        ap_const_lv10_1FF when (and_ln245_1_fu_310_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln245_3_fu_495_p3 <= 
        select_ln245_2_fu_477_p3 when (xor_ln245_3_fu_316_p2(0) = '1') else 
        tmp_1_fu_485_p4;
    select_ln245_4_fu_503_p3 <= 
        ap_const_lv10_1FF when (and_ln245_2_fu_353_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln245_5_fu_521_p3 <= 
        select_ln245_4_fu_503_p3 when (xor_ln245_5_fu_359_p2(0) = '1') else 
        tmp_2_fu_511_p4;
    select_ln245_6_fu_534_p3 <= 
        ap_const_lv10_1FF when (and_ln245_3_fu_396_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln245_7_fu_552_p3 <= 
        select_ln245_6_fu_534_p3 when (xor_ln245_7_fu_402_p2(0) = '1') else 
        tmp_3_fu_542_p4;
    select_ln245_8_fu_565_p3 <= 
        ap_const_lv10_1FF when (and_ln245_4_fu_439_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln245_9_fu_583_p3 <= 
        select_ln245_8_fu_565_p3 when (xor_ln245_9_fu_445_p2(0) = '1') else 
        tmp_4_fu_573_p4;
    select_ln245_fu_451_p3 <= 
        ap_const_lv10_1FF when (and_ln245_fu_267_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln66_1_fu_188_p1 <= data_2_val;
    select_ln66_1_fu_188_p2 <= data_3_val;
    select_ln66_1_fu_188_p3 <= 
        select_ln66_1_fu_188_p1 when (xor_ln66_1_fu_182_p2(0) = '1') else 
        select_ln66_1_fu_188_p2;
    select_ln66_2_fu_208_p3 <= 
        select_ln66_fu_168_p3 when (xor_ln66_2_fu_202_p2(0) = '1') else 
        select_ln66_1_fu_188_p3;
    select_ln66_fu_168_p1 <= data_0_val;
    select_ln66_fu_168_p2 <= data_1_val;
    select_ln66_fu_168_p3 <= 
        select_ln66_fu_168_p1 when (xor_ln66_fu_162_p2(0) = '1') else 
        select_ln66_fu_168_p2;
        sext_ln245_1_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_max_fu_226_p3),19));

        sext_ln245_2_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_1_val_read_reg_786),19));

        sext_ln245_3_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_2_val_read_reg_781),19));

        sext_ln245_4_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_3_val_read_reg_776),19));

        sext_ln245_5_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_4_val_read_reg_769),19));

        sext_ln245_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_0_val_read_reg_791),19));

        sext_ln268_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(invert_table_q0),30));

    sub_ln245_1_fu_282_p2 <= std_logic_vector(signed(sext_ln245_2_fu_279_p1) - signed(sext_ln245_1_fu_235_p1));
    sub_ln245_2_fu_325_p2 <= std_logic_vector(signed(sext_ln245_3_fu_322_p1) - signed(sext_ln245_1_fu_235_p1));
    sub_ln245_3_fu_368_p2 <= std_logic_vector(signed(sext_ln245_4_fu_365_p1) - signed(sext_ln245_1_fu_235_p1));
    sub_ln245_4_fu_411_p2 <= std_logic_vector(signed(sext_ln245_5_fu_408_p1) - signed(sext_ln245_1_fu_235_p1));
    sub_ln245_fu_239_p2 <= std_logic_vector(signed(sext_ln245_fu_232_p1) - signed(sext_ln245_1_fu_235_p1));
    tmp_10_fu_339_p3 <= sub_ln245_2_fu_325_p2(17 downto 17);
    tmp_11_fu_374_p3 <= sub_ln245_3_fu_368_p2(18 downto 18);
    tmp_12_fu_382_p3 <= sub_ln245_3_fu_368_p2(17 downto 17);
    tmp_13_fu_417_p3 <= sub_ln245_4_fu_411_p2(18 downto 18);
    tmp_14_fu_425_p3 <= sub_ln245_4_fu_411_p2(17 downto 17);
    tmp_1_fu_485_p4 <= sub_ln245_1_fu_282_p2(17 downto 8);
    tmp_2_fu_511_p4 <= sub_ln245_2_fu_325_p2(17 downto 8);
    tmp_3_fu_542_p4 <= sub_ln245_3_fu_368_p2(17 downto 8);
    tmp_4_fu_573_p4 <= sub_ln245_4_fu_411_p2(17 downto 8);
    tmp_5_fu_245_p3 <= sub_ln245_fu_239_p2(18 downto 18);
    tmp_6_fu_253_p3 <= sub_ln245_fu_239_p2(17 downto 17);
    tmp_7_fu_288_p3 <= sub_ln245_1_fu_282_p2(18 downto 18);
    tmp_8_fu_296_p3 <= sub_ln245_1_fu_282_p2(17 downto 17);
    tmp_9_fu_331_p3 <= sub_ln245_2_fu_325_p2(18 downto 18);
    tmp_fu_459_p4 <= sub_ln245_fu_239_p2(17 downto 8);
    tmp_s_fu_625_p4 <= exp_sum_fu_619_p2(17 downto 8);
    x_max_fu_226_p3 <= 
        select_ln66_2_reg_796 when (xor_ln66_3_fu_220_p2(0) = '1') else 
        data_4_val_read_reg_769;
    xor_ln245_1_fu_273_p2 <= (tmp_6_fu_253_p3 xor tmp_5_fu_245_p3);
    xor_ln245_2_fu_304_p2 <= (tmp_7_fu_288_p3 xor ap_const_lv1_1);
    xor_ln245_3_fu_316_p2 <= (tmp_8_fu_296_p3 xor tmp_7_fu_288_p3);
    xor_ln245_4_fu_347_p2 <= (tmp_9_fu_331_p3 xor ap_const_lv1_1);
    xor_ln245_5_fu_359_p2 <= (tmp_9_fu_331_p3 xor tmp_10_fu_339_p3);
    xor_ln245_6_fu_390_p2 <= (tmp_11_fu_374_p3 xor ap_const_lv1_1);
    xor_ln245_7_fu_402_p2 <= (tmp_12_fu_382_p3 xor tmp_11_fu_374_p3);
    xor_ln245_8_fu_433_p2 <= (tmp_13_fu_417_p3 xor ap_const_lv1_1);
    xor_ln245_9_fu_445_p2 <= (tmp_14_fu_425_p3 xor tmp_13_fu_417_p3);
    xor_ln245_fu_261_p2 <= (tmp_5_fu_245_p3 xor ap_const_lv1_1);
    xor_ln66_1_fu_182_p2 <= (icmp_ln66_1_fu_176_p2 xor ap_const_lv1_1);
    xor_ln66_2_fu_202_p2 <= (icmp_ln66_2_fu_196_p2 xor ap_const_lv1_1);
    xor_ln66_3_fu_220_p2 <= (icmp_ln66_3_fu_216_p2 xor ap_const_lv1_1);
    xor_ln66_fu_162_p2 <= (icmp_ln66_fu_156_p2 xor ap_const_lv1_1);
    zext_ln255_1_fu_600_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln245_3_reg_807),64));
    zext_ln255_2_fu_529_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln245_5_fu_521_p3),64));
    zext_ln255_3_fu_560_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln245_7_fu_552_p3),64));
    zext_ln255_4_fu_591_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln245_9_fu_583_p3),64));
    zext_ln255_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln245_1_reg_802),64));
    zext_ln265_fu_635_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_625_p4),64));
end behav;
