-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_16_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_17_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_20_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_25_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_29_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_30_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_31_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_35_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_36_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_46_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_47_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_48_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_49_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_51_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_52_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_54_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_55_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_56_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_58_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_59_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_60_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_27_fu_348_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_fu_358_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_1_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_26_fu_344_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_1_fu_376_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_2_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_25_fu_340_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_2_fu_394_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_3_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_24_fu_336_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_3_fu_412_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_4_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_23_fu_332_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_4_fu_430_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_5_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_22_fu_328_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_5_fu_448_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_6_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_21_fu_324_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_6_fu_466_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_7_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_20_fu_320_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_7_fu_484_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_8_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_19_fu_316_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_8_fu_502_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_9_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_18_fu_312_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_9_fu_520_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_10_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_17_fu_308_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_10_fu_538_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_11_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_16_fu_304_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_11_fu_556_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_12_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_15_fu_300_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_12_fu_574_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_13_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_14_fu_296_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_13_fu_592_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_14_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_13_fu_292_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_14_fu_610_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_15_fu_622_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_12_fu_288_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_15_fu_628_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_16_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_11_fu_284_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_16_fu_646_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_17_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_10_fu_280_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_17_fu_664_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_18_fu_676_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_9_fu_276_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_18_fu_682_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_19_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_8_fu_272_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_19_fu_700_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_20_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_7_fu_268_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_20_fu_718_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_21_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_6_fu_264_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_21_fu_736_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_22_fu_748_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_5_fu_260_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_22_fu_754_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_23_fu_766_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_4_fu_256_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_23_fu_772_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_24_fu_784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_3_fu_252_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_24_fu_790_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_25_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_2_fu_248_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_25_fu_808_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_26_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_1_fu_244_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_26_fu_826_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_27_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_fu_240_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_27_fu_844_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln45_fu_366_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_1_fu_384_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_2_fu_402_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_3_fu_420_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_4_fu_438_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_5_fu_456_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_6_fu_474_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_7_fu_492_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_8_fu_510_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_9_fu_528_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_10_fu_546_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_11_fu_564_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_12_fu_582_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_13_fu_600_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_14_fu_618_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_15_fu_636_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_16_fu_654_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_17_fu_672_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_18_fu_690_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_19_fu_708_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_20_fu_726_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_21_fu_744_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_22_fu_762_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_23_fu_780_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_24_fu_798_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_25_fu_816_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_26_fu_834_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_27_fu_852_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln45_fu_366_p1;
    ap_return_1 <= zext_ln45_1_fu_384_p1;
    ap_return_10 <= zext_ln45_10_fu_546_p1;
    ap_return_11 <= zext_ln45_11_fu_564_p1;
    ap_return_12 <= zext_ln45_12_fu_582_p1;
    ap_return_13 <= zext_ln45_13_fu_600_p1;
    ap_return_14 <= zext_ln45_14_fu_618_p1;
    ap_return_15 <= zext_ln45_15_fu_636_p1;
    ap_return_16 <= zext_ln45_16_fu_654_p1;
    ap_return_17 <= zext_ln45_17_fu_672_p1;
    ap_return_18 <= zext_ln45_18_fu_690_p1;
    ap_return_19 <= zext_ln45_19_fu_708_p1;
    ap_return_2 <= zext_ln45_2_fu_402_p1;
    ap_return_20 <= zext_ln45_20_fu_726_p1;
    ap_return_21 <= zext_ln45_21_fu_744_p1;
    ap_return_22 <= zext_ln45_22_fu_762_p1;
    ap_return_23 <= zext_ln45_23_fu_780_p1;
    ap_return_24 <= zext_ln45_24_fu_798_p1;
    ap_return_25 <= zext_ln45_25_fu_816_p1;
    ap_return_26 <= zext_ln45_26_fu_834_p1;
    ap_return_27 <= zext_ln45_27_fu_852_p1;
    ap_return_3 <= zext_ln45_3_fu_420_p1;
    ap_return_4 <= zext_ln45_4_fu_438_p1;
    ap_return_5 <= zext_ln45_5_fu_456_p1;
    ap_return_6 <= zext_ln45_6_fu_474_p1;
    ap_return_7 <= zext_ln45_7_fu_492_p1;
    ap_return_8 <= zext_ln45_8_fu_510_p1;
    ap_return_9 <= zext_ln45_9_fu_528_p1;
    datareg_10_fu_538_p3 <= 
        trunc_ln42_17_fu_308_p1 when (icmp_ln45_10_fu_532_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_11_fu_556_p3 <= 
        trunc_ln42_16_fu_304_p1 when (icmp_ln45_11_fu_550_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_12_fu_574_p3 <= 
        trunc_ln42_15_fu_300_p1 when (icmp_ln45_12_fu_568_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_13_fu_592_p3 <= 
        trunc_ln42_14_fu_296_p1 when (icmp_ln45_13_fu_586_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_14_fu_610_p3 <= 
        trunc_ln42_13_fu_292_p1 when (icmp_ln45_14_fu_604_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_15_fu_628_p3 <= 
        trunc_ln42_12_fu_288_p1 when (icmp_ln45_15_fu_622_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_16_fu_646_p3 <= 
        trunc_ln42_11_fu_284_p1 when (icmp_ln45_16_fu_640_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_17_fu_664_p3 <= 
        trunc_ln42_10_fu_280_p1 when (icmp_ln45_17_fu_658_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_18_fu_682_p3 <= 
        trunc_ln42_9_fu_276_p1 when (icmp_ln45_18_fu_676_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_19_fu_700_p3 <= 
        trunc_ln42_8_fu_272_p1 when (icmp_ln45_19_fu_694_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_1_fu_376_p3 <= 
        trunc_ln42_26_fu_344_p1 when (icmp_ln45_1_fu_370_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_20_fu_718_p3 <= 
        trunc_ln42_7_fu_268_p1 when (icmp_ln45_20_fu_712_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_21_fu_736_p3 <= 
        trunc_ln42_6_fu_264_p1 when (icmp_ln45_21_fu_730_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_22_fu_754_p3 <= 
        trunc_ln42_5_fu_260_p1 when (icmp_ln45_22_fu_748_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_23_fu_772_p3 <= 
        trunc_ln42_4_fu_256_p1 when (icmp_ln45_23_fu_766_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_24_fu_790_p3 <= 
        trunc_ln42_3_fu_252_p1 when (icmp_ln45_24_fu_784_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_25_fu_808_p3 <= 
        trunc_ln42_2_fu_248_p1 when (icmp_ln45_25_fu_802_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_26_fu_826_p3 <= 
        trunc_ln42_1_fu_244_p1 when (icmp_ln45_26_fu_820_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_27_fu_844_p3 <= 
        trunc_ln42_fu_240_p1 when (icmp_ln45_27_fu_838_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_2_fu_394_p3 <= 
        trunc_ln42_25_fu_340_p1 when (icmp_ln45_2_fu_388_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_3_fu_412_p3 <= 
        trunc_ln42_24_fu_336_p1 when (icmp_ln45_3_fu_406_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_4_fu_430_p3 <= 
        trunc_ln42_23_fu_332_p1 when (icmp_ln45_4_fu_424_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_5_fu_448_p3 <= 
        trunc_ln42_22_fu_328_p1 when (icmp_ln45_5_fu_442_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_6_fu_466_p3 <= 
        trunc_ln42_21_fu_324_p1 when (icmp_ln45_6_fu_460_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_7_fu_484_p3 <= 
        trunc_ln42_20_fu_320_p1 when (icmp_ln45_7_fu_478_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_8_fu_502_p3 <= 
        trunc_ln42_19_fu_316_p1 when (icmp_ln45_8_fu_496_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_9_fu_520_p3 <= 
        trunc_ln42_18_fu_312_p1 when (icmp_ln45_9_fu_514_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_fu_358_p3 <= 
        trunc_ln42_27_fu_348_p1 when (icmp_ln45_fu_352_p2(0) = '1') else 
        ap_const_lv15_0;
    icmp_ln45_10_fu_532_p2 <= "1" when (signed(data_25_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_11_fu_550_p2 <= "1" when (signed(data_29_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_12_fu_568_p2 <= "1" when (signed(data_30_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_13_fu_586_p2 <= "1" when (signed(data_31_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_14_fu_604_p2 <= "1" when (signed(data_35_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_15_fu_622_p2 <= "1" when (signed(data_36_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_16_fu_640_p2 <= "1" when (signed(data_46_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_17_fu_658_p2 <= "1" when (signed(data_47_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_18_fu_676_p2 <= "1" when (signed(data_48_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_19_fu_694_p2 <= "1" when (signed(data_49_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_1_fu_370_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_20_fu_712_p2 <= "1" when (signed(data_51_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_21_fu_730_p2 <= "1" when (signed(data_52_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_22_fu_748_p2 <= "1" when (signed(data_54_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_23_fu_766_p2 <= "1" when (signed(data_55_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_24_fu_784_p2 <= "1" when (signed(data_56_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_25_fu_802_p2 <= "1" when (signed(data_58_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_26_fu_820_p2 <= "1" when (signed(data_59_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_27_fu_838_p2 <= "1" when (signed(data_60_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_2_fu_388_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_3_fu_406_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_4_fu_424_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_5_fu_442_p2 <= "1" when (signed(data_8_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_6_fu_460_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_7_fu_478_p2 <= "1" when (signed(data_16_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_8_fu_496_p2 <= "1" when (signed(data_17_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_9_fu_514_p2 <= "1" when (signed(data_20_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_352_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv16_0)) else "0";
    trunc_ln42_10_fu_280_p1 <= data_47_val(15 - 1 downto 0);
    trunc_ln42_11_fu_284_p1 <= data_46_val(15 - 1 downto 0);
    trunc_ln42_12_fu_288_p1 <= data_36_val(15 - 1 downto 0);
    trunc_ln42_13_fu_292_p1 <= data_35_val(15 - 1 downto 0);
    trunc_ln42_14_fu_296_p1 <= data_31_val(15 - 1 downto 0);
    trunc_ln42_15_fu_300_p1 <= data_30_val(15 - 1 downto 0);
    trunc_ln42_16_fu_304_p1 <= data_29_val(15 - 1 downto 0);
    trunc_ln42_17_fu_308_p1 <= data_25_val(15 - 1 downto 0);
    trunc_ln42_18_fu_312_p1 <= data_20_val(15 - 1 downto 0);
    trunc_ln42_19_fu_316_p1 <= data_17_val(15 - 1 downto 0);
    trunc_ln42_1_fu_244_p1 <= data_59_val(15 - 1 downto 0);
    trunc_ln42_20_fu_320_p1 <= data_16_val(15 - 1 downto 0);
    trunc_ln42_21_fu_324_p1 <= data_9_val(15 - 1 downto 0);
    trunc_ln42_22_fu_328_p1 <= data_8_val(15 - 1 downto 0);
    trunc_ln42_23_fu_332_p1 <= data_7_val(15 - 1 downto 0);
    trunc_ln42_24_fu_336_p1 <= data_5_val(15 - 1 downto 0);
    trunc_ln42_25_fu_340_p1 <= data_4_val(15 - 1 downto 0);
    trunc_ln42_26_fu_344_p1 <= data_1_val(15 - 1 downto 0);
    trunc_ln42_27_fu_348_p1 <= data_0_val(15 - 1 downto 0);
    trunc_ln42_2_fu_248_p1 <= data_58_val(15 - 1 downto 0);
    trunc_ln42_3_fu_252_p1 <= data_56_val(15 - 1 downto 0);
    trunc_ln42_4_fu_256_p1 <= data_55_val(15 - 1 downto 0);
    trunc_ln42_5_fu_260_p1 <= data_54_val(15 - 1 downto 0);
    trunc_ln42_6_fu_264_p1 <= data_52_val(15 - 1 downto 0);
    trunc_ln42_7_fu_268_p1 <= data_51_val(15 - 1 downto 0);
    trunc_ln42_8_fu_272_p1 <= data_49_val(15 - 1 downto 0);
    trunc_ln42_9_fu_276_p1 <= data_48_val(15 - 1 downto 0);
    trunc_ln42_fu_240_p1 <= data_60_val(15 - 1 downto 0);
    zext_ln45_10_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_10_fu_538_p3),16));
    zext_ln45_11_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_11_fu_556_p3),16));
    zext_ln45_12_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_12_fu_574_p3),16));
    zext_ln45_13_fu_600_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_13_fu_592_p3),16));
    zext_ln45_14_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_14_fu_610_p3),16));
    zext_ln45_15_fu_636_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_15_fu_628_p3),16));
    zext_ln45_16_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_16_fu_646_p3),16));
    zext_ln45_17_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_17_fu_664_p3),16));
    zext_ln45_18_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_18_fu_682_p3),16));
    zext_ln45_19_fu_708_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_19_fu_700_p3),16));
    zext_ln45_1_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_1_fu_376_p3),16));
    zext_ln45_20_fu_726_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_20_fu_718_p3),16));
    zext_ln45_21_fu_744_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_21_fu_736_p3),16));
    zext_ln45_22_fu_762_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_22_fu_754_p3),16));
    zext_ln45_23_fu_780_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_23_fu_772_p3),16));
    zext_ln45_24_fu_798_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_24_fu_790_p3),16));
    zext_ln45_25_fu_816_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_25_fu_808_p3),16));
    zext_ln45_26_fu_834_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_26_fu_826_p3),16));
    zext_ln45_27_fu_852_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_27_fu_844_p3),16));
    zext_ln45_2_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_2_fu_394_p3),16));
    zext_ln45_3_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_3_fu_412_p3),16));
    zext_ln45_4_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_4_fu_430_p3),16));
    zext_ln45_5_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_5_fu_448_p3),16));
    zext_ln45_6_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_6_fu_466_p3),16));
    zext_ln45_7_fu_492_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_7_fu_484_p3),16));
    zext_ln45_8_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_8_fu_502_p3),16));
    zext_ln45_9_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_9_fu_520_p3),16));
    zext_ln45_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_fu_358_p3),16));
end behav;
