// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_18_7_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_9_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [5:0] data_0_val;
input  [5:0] data_1_val;
input  [5:0] data_3_val;
input  [5:0] data_4_val;
input  [5:0] data_5_val;
input  [5:0] data_6_val;
input  [5:0] data_7_val;
input  [5:0] data_9_val;
input  [5:0] data_11_val;
input  [5:0] data_12_val;
input  [5:0] data_13_val;
input  [5:0] data_14_val;
input  [5:0] data_15_val;
input  [5:0] data_17_val;
input  [5:0] data_18_val;
input  [5:0] data_19_val;
input  [5:0] data_20_val;
input  [5:0] data_21_val;
input  [5:0] data_22_val;
input  [5:0] data_23_val;
input  [5:0] data_24_val;
input  [5:0] data_25_val;
input  [5:0] data_26_val;
input  [5:0] data_27_val;
input  [5:0] data_28_val;
input  [5:0] data_29_val;
input  [5:0] data_31_val;
output  [17:0] ap_return_0;
output  [17:0] ap_return_1;
output  [17:0] ap_return_2;
output  [17:0] ap_return_3;
output  [17:0] ap_return_4;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [13:0] add_ln58_666_fu_1601_p2;
reg   [13:0] add_ln58_666_reg_1988;
wire    ap_block_pp0_stage0_11001;
wire   [13:0] add_ln58_670_fu_1649_p2;
reg   [13:0] add_ln58_670_reg_1993;
wire   [13:0] add_ln58_676_fu_1697_p2;
reg   [13:0] add_ln58_676_reg_1998;
wire   [13:0] add_ln58_678_fu_1713_p2;
reg   [13:0] add_ln58_678_reg_2003;
wire   [13:0] add_ln58_680_fu_1729_p2;
reg   [13:0] add_ln58_680_reg_2008;
wire   [13:0] add_ln58_686_fu_1775_p2;
reg   [13:0] add_ln58_686_reg_2013;
wire   [13:0] add_ln58_690_fu_1805_p2;
reg   [13:0] add_ln58_690_reg_2018;
wire   [13:0] add_ln58_693_fu_1831_p2;
reg   [13:0] add_ln58_693_reg_2023;
wire   [14:0] add_ln58_701_fu_1897_p2;
reg   [14:0] add_ln58_701_reg_2028;
wire   [5:0] mul_ln73_86_fu_270_p0;
wire   [10:0] zext_ln73_294_fu_936_p1;
wire   [5:0] mul_ln73_86_fu_270_p1;
wire    ap_block_pp0_stage0;
wire   [5:0] mul_ln73_87_fu_286_p0;
wire  signed [5:0] mul_ln73_87_fu_286_p1;
wire   [5:0] mul_ln73_fu_299_p0;
wire   [5:0] mul_ln73_fu_299_p1;
wire   [10:0] p_shl85_fu_814_p3;
wire   [10:0] zext_ln73_292_fu_810_p1;
wire   [11:0] zext_ln73_fu_828_p1;
wire   [11:0] sub_ln73_366_fu_832_p2;
wire   [10:0] p_shl82_fu_846_p3;
wire   [10:0] zext_ln70_fu_842_p1;
wire   [10:0] tmp_fu_860_p3;
wire   [11:0] zext_ln73_471_fu_868_p1;
wire   [11:0] sub_ln73_368_fu_872_p2;
wire   [10:0] p_shl79_fu_886_p3;
wire   [10:0] zext_ln73_293_fu_882_p1;
wire   [11:0] zext_ln73_472_fu_900_p1;
wire   [11:0] sub_ln73_370_fu_904_p2;
wire   [10:0] tmp_928_fu_914_p3;
wire   [11:0] zext_ln73_473_fu_922_p1;
wire   [11:0] sub_ln73_371_fu_926_p2;
wire   [10:0] tmp_929_fu_942_p3;
wire   [11:0] zext_ln73_474_fu_950_p1;
wire   [11:0] sub_ln73_372_fu_954_p2;
wire   [10:0] tmp_930_fu_968_p3;
wire   [11:0] zext_ln73_475_fu_976_p1;
wire   [11:0] sub_ln73_373_fu_980_p2;
wire   [10:0] zext_ln73_295_fu_964_p1;
wire   [10:0] tmp_931_fu_996_p3;
wire   [11:0] zext_ln73_476_fu_1004_p1;
wire   [11:0] sub_ln73_375_fu_1008_p2;
wire   [10:0] tmp_932_fu_1018_p3;
wire   [11:0] zext_ln73_477_fu_1026_p1;
wire   [11:0] sub_ln73_376_fu_1030_p2;
wire   [10:0] p_shl65_fu_1044_p3;
wire   [10:0] zext_ln70_3_fu_1040_p1;
wire   [10:0] p_shl64_fu_1062_p3;
wire   [10:0] zext_ln70_4_fu_1058_p1;
wire   [10:0] tmp_933_fu_1076_p3;
wire   [11:0] zext_ln73_478_fu_1084_p1;
wire   [11:0] sub_ln73_379_fu_1088_p2;
wire   [10:0] p_shl61_fu_1102_p3;
wire   [10:0] zext_ln70_5_fu_1098_p1;
wire   [10:0] p_shl60_fu_1120_p3;
wire   [10:0] zext_ln73_296_fu_1116_p1;
wire   [6:0] tmp_934_fu_1138_p3;
wire   [11:0] zext_ln73_480_fu_1146_p1;
wire   [11:0] zext_ln73_479_fu_1134_p1;
wire   [11:0] sub_ln73_382_fu_1150_p2;
wire   [10:0] tmp_935_fu_1160_p3;
wire   [11:0] zext_ln73_481_fu_1168_p1;
wire   [11:0] sub_ln73_383_fu_1172_p2;
wire   [10:0] tmp_936_fu_1182_p3;
wire   [11:0] zext_ln73_482_fu_1190_p1;
wire   [11:0] sub_ln73_384_fu_1194_p2;
wire   [7:0] tmp_937_fu_1212_p3;
wire   [9:0] p_shl54_fu_1204_p3;
wire   [9:0] zext_ln73_483_fu_1220_p1;
wire   [10:0] tmp_938_fu_1230_p3;
wire   [11:0] zext_ln73_484_fu_1238_p1;
wire   [10:0] tmp_939_fu_1248_p3;
wire   [11:0] zext_ln73_485_fu_1256_p1;
wire   [11:0] sub_ln73_387_fu_1260_p2;
wire   [10:0] tmp_940_fu_1279_p3;
wire   [11:0] zext_ln73_486_fu_1287_p1;
wire   [11:0] sub_ln73_388_fu_1291_p2;
wire   [10:0] zext_ln73_298_fu_1275_p1;
wire   [11:0] mul_ln73_87_fu_286_p2;
wire   [10:0] tmp_941_fu_1315_p3;
wire   [11:0] zext_ln73_487_fu_1323_p1;
wire   [11:0] sub_ln73_390_fu_1327_p2;
wire   [9:0] tmp_942_fu_1337_p3;
wire   [10:0] zext_ln73_488_fu_1345_p1;
wire   [10:0] zext_ln73_299_fu_1311_p1;
wire   [10:0] tmp_943_fu_1359_p3;
wire   [11:0] zext_ln73_489_fu_1367_p1;
wire   [11:0] sub_ln73_391_fu_1371_p2;
wire   [10:0] zext_ln73_300_fu_1355_p1;
wire   [10:0] p_shl45_fu_1391_p3;
wire   [10:0] zext_ln70_6_fu_1387_p1;
wire   [10:0] tmp_944_fu_1405_p3;
wire   [11:0] zext_ln73_490_fu_1413_p1;
wire   [11:0] sub_ln73_394_fu_1417_p2;
wire   [10:0] tmp_945_fu_1427_p3;
wire   [11:0] zext_ln73_491_fu_1435_p1;
wire   [11:0] sub_ln73_395_fu_1439_p2;
wire   [10:0] tmp_946_fu_1449_p3;
wire   [11:0] zext_ln73_492_fu_1457_p1;
wire   [11:0] sub_ln73_396_fu_1461_p2;
wire   [6:0] tmp_947_fu_1479_p3;
wire   [10:0] p_shl40_fu_1471_p3;
wire   [10:0] zext_ln73_493_fu_1487_p1;
wire   [10:0] tmp_948_fu_1497_p3;
wire   [11:0] zext_ln73_494_fu_1505_p1;
wire   [11:0] sub_ln73_398_fu_1509_p2;
wire   [10:0] sub_ln73_fu_822_p2;
wire   [10:0] sub_ln73_367_fu_854_p2;
wire   [10:0] sub_ln73_369_fu_894_p2;
wire   [10:0] mul_ln73_fu_299_p2;
wire   [10:0] mul_ln73_86_fu_270_p2;
wire   [10:0] sub_ln73_374_fu_990_p2;
wire   [10:0] sub_ln73_377_fu_1052_p2;
wire   [10:0] sub_ln73_378_fu_1070_p2;
wire   [10:0] sub_ln73_380_fu_1110_p2;
wire   [10:0] sub_ln73_381_fu_1128_p2;
wire   [9:0] sub_ln73_385_fu_1224_p2;
wire  signed [11:0] sub_ln73_386_fu_1242_p2;
wire  signed [12:0] sext_ln73_fu_960_p1;
wire  signed [12:0] sext_ln70_3_fu_1266_p1;
wire   [12:0] add_ln58_fu_1571_p2;
wire   [11:0] zext_ln58_479_fu_1551_p1;
wire   [11:0] add_ln58_664_fu_1581_p2;
wire  signed [12:0] sext_ln58_285_fu_1587_p1;
wire   [12:0] zext_ln58_472_fu_1523_p1;
wire   [12:0] add_ln58_665_fu_1591_p2;
wire  signed [13:0] sext_ln58_286_fu_1597_p1;
wire  signed [13:0] sext_ln58_284_fu_1577_p1;
wire   [10:0] sub_ln73_389_fu_1301_p2;
wire   [10:0] sub_ln73_392_fu_1381_p2;
wire   [10:0] sub_ln73_393_fu_1399_p2;
wire  signed [12:0] sext_ln73_1_fu_986_p1;
wire  signed [12:0] sext_ln73_3_fu_1297_p1;
wire   [12:0] add_ln58_667_fu_1619_p2;
wire   [11:0] zext_ln58_474_fu_1531_p1;
wire   [11:0] add_ln58_668_fu_1629_p2;
wire   [12:0] zext_ln58_485_fu_1635_p1;
wire  signed [12:0] mul_ln73_499_cast_fu_1423_p1;
wire   [12:0] add_ln58_669_fu_1639_p2;
wire  signed [13:0] sext_ln58_289_fu_1645_p1;
wire  signed [13:0] sext_ln58_288_fu_1625_p1;
wire  signed [12:0] sext_ln70_2_fu_1178_p1;
wire  signed [12:0] mul_ln73_500_cast_fu_1445_p1;
wire   [12:0] add_ln58_671_fu_1655_p2;
wire  signed [13:0] sext_ln58_291_fu_1661_p1;
wire  signed [13:0] mul_ln73_482_cast_fu_1094_p1;
wire   [11:0] zext_ln58_fu_1519_p1;
wire   [11:0] zext_ln58_473_fu_1527_p1;
wire   [11:0] add_ln58_673_fu_1671_p2;
wire   [11:0] zext_ln58_482_fu_1607_p1;
wire   [11:0] add_ln58_674_fu_1681_p2;
wire  signed [13:0] sext_ln58_292_fu_1687_p1;
wire   [13:0] zext_ln58_486_fu_1677_p1;
wire   [13:0] add_ln58_675_fu_1691_p2;
wire   [13:0] add_ln58_672_fu_1665_p2;
wire  signed [12:0] mul_ln73_479_cast_fu_1036_p1;
wire  signed [12:0] sext_ln73_2_fu_1200_p1;
wire   [12:0] add_ln58_677_fu_1703_p2;
wire  signed [13:0] sext_ln58_294_fu_1709_p1;
wire  signed [13:0] mul_ln73_471_cast_fu_910_p1;
wire  signed [12:0] sext_ln73_4_fu_1333_p1;
wire  signed [12:0] sext_ln73_5_fu_1377_p1;
wire   [12:0] add_ln58_679_fu_1719_p2;
wire  signed [13:0] sext_ln58_296_fu_1725_p1;
wire  signed [13:0] sext_ln58_283_fu_1567_p1;
wire   [11:0] zext_ln58_476_fu_1539_p1;
wire   [11:0] zext_ln58_478_fu_1547_p1;
wire   [11:0] add_ln58_682_fu_1735_p2;
wire   [12:0] zext_ln58_487_fu_1741_p1;
wire  signed [12:0] mul_ln73_501_cast_fu_1467_p1;
wire   [12:0] add_ln58_683_fu_1745_p2;
wire   [11:0] add_ln58_684_fu_1755_p2;
wire   [12:0] zext_ln58_488_fu_1761_p1;
wire   [12:0] zext_ln58_480_fu_1555_p1;
wire   [12:0] add_ln58_685_fu_1765_p2;
wire   [13:0] zext_ln58_489_fu_1771_p1;
wire  signed [13:0] sext_ln58_298_fu_1751_p1;
wire   [10:0] sub_ln73_397_fu_1491_p2;
wire  signed [12:0] mul_ln73_467_cast_fu_838_p1;
wire  signed [12:0] sext_ln70_fu_878_p1;
wire   [12:0] add_ln58_688_fu_1785_p2;
wire  signed [12:0] sext_ln70_1_fu_932_p1;
wire  signed [12:0] mul_ln73_478_cast_fu_1014_p1;
wire   [12:0] add_ln58_689_fu_1795_p2;
wire  signed [13:0] sext_ln58_302_fu_1801_p1;
wire  signed [13:0] sext_ln58_301_fu_1791_p1;
wire  signed [12:0] mul_ln73_485_cast_fu_1156_p1;
wire  signed [12:0] sext_ln58_282_fu_1563_p1;
wire   [12:0] add_ln58_691_fu_1811_p2;
wire  signed [12:0] sext_ln70_4_fu_1307_p1;
wire  signed [12:0] sext_ln58_fu_1515_p1;
wire   [12:0] add_ln58_692_fu_1821_p2;
wire  signed [13:0] sext_ln58_305_fu_1827_p1;
wire  signed [13:0] sext_ln58_304_fu_1817_p1;
wire   [11:0] zext_ln58_475_fu_1535_p1;
wire   [11:0] zext_ln58_477_fu_1543_p1;
wire   [11:0] add_ln58_695_fu_1837_p2;
wire   [10:0] zext_ln58_481_fu_1559_p1;
wire   [10:0] add_ln73_fu_1349_p2;
wire   [10:0] add_ln58_696_fu_1847_p2;
wire   [12:0] zext_ln58_492_fu_1853_p1;
wire   [12:0] zext_ln58_491_fu_1843_p1;
wire   [12:0] add_ln58_697_fu_1857_p2;
wire   [11:0] zext_ln58_483_fu_1611_p1;
wire   [11:0] zext_ln58_484_fu_1615_p1;
wire   [11:0] add_ln58_698_fu_1867_p2;
wire   [11:0] zext_ln58_490_fu_1781_p1;
wire   [11:0] add_ln58_699_fu_1877_p2;
wire  signed [13:0] sext_ln58_307_fu_1883_p1;
wire   [13:0] zext_ln58_494_fu_1873_p1;
wire   [13:0] add_ln58_700_fu_1887_p2;
wire  signed [14:0] sext_ln58_308_fu_1893_p1;
wire   [14:0] zext_ln58_493_fu_1863_p1;
wire  signed [14:0] sext_ln58_297_fu_1915_p1;
wire  signed [14:0] sext_ln58_295_fu_1912_p1;
wire  signed [14:0] sext_ln58_299_fu_1924_p1;
wire   [14:0] add_ln58_681_fu_1918_p2;
wire   [14:0] add_ln58_687_fu_1927_p2;
wire  signed [14:0] sext_ln58_306_fu_1940_p1;
wire  signed [14:0] sext_ln58_303_fu_1937_p1;
wire   [14:0] add_ln58_694_fu_1943_p2;
wire   [14:0] add_ln58_702_fu_1949_p2;
wire  signed [17:0] sext_ln58_287_fu_1903_p1;
wire  signed [17:0] sext_ln58_290_fu_1906_p1;
wire  signed [17:0] sext_ln58_293_fu_1909_p1;
wire  signed [17:0] sext_ln58_300_fu_1933_p1;
wire  signed [17:0] sext_ln68_fu_1954_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [11:0] mul_ln73_87_fu_286_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

myproject_mul_6ns_6ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_1_U356(
    .din0(mul_ln73_86_fu_270_p0),
    .din1(mul_ln73_86_fu_270_p1),
    .dout(mul_ln73_86_fu_270_p2)
);

myproject_mul_6ns_6s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_6ns_6s_12_1_1_U357(
    .din0(mul_ln73_87_fu_286_p0),
    .din1(mul_ln73_87_fu_286_p1),
    .dout(mul_ln73_87_fu_286_p2)
);

myproject_mul_6ns_6ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_1_U358(
    .din0(mul_ln73_fu_299_p0),
    .din1(mul_ln73_fu_299_p1),
    .dout(mul_ln73_fu_299_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_666_reg_1988 <= add_ln58_666_fu_1601_p2;
        add_ln58_670_reg_1993 <= add_ln58_670_fu_1649_p2;
        add_ln58_676_reg_1998 <= add_ln58_676_fu_1697_p2;
        add_ln58_678_reg_2003[13 : 5] <= add_ln58_678_fu_1713_p2[13 : 5];
        add_ln58_680_reg_2008[13 : 5] <= add_ln58_680_fu_1729_p2[13 : 5];
        add_ln58_686_reg_2013 <= add_ln58_686_fu_1775_p2;
        add_ln58_690_reg_2018[13 : 5] <= add_ln58_690_fu_1805_p2[13 : 5];
        add_ln58_693_reg_2023 <= add_ln58_693_fu_1831_p2;
        add_ln58_701_reg_2028 <= add_ln58_701_fu_1897_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_664_fu_1581_p2 = ($signed(zext_ln58_479_fu_1551_p1) + $signed(12'd3520));

assign add_ln58_665_fu_1591_p2 = ($signed(sext_ln58_285_fu_1587_p1) + $signed(zext_ln58_472_fu_1523_p1));

assign add_ln58_666_fu_1601_p2 = ($signed(sext_ln58_286_fu_1597_p1) + $signed(sext_ln58_284_fu_1577_p1));

assign add_ln58_667_fu_1619_p2 = ($signed(sext_ln73_1_fu_986_p1) + $signed(sext_ln73_3_fu_1297_p1));

assign add_ln58_668_fu_1629_p2 = (zext_ln58_474_fu_1531_p1 + 12'd768);

assign add_ln58_669_fu_1639_p2 = ($signed(zext_ln58_485_fu_1635_p1) + $signed(mul_ln73_499_cast_fu_1423_p1));

assign add_ln58_670_fu_1649_p2 = ($signed(sext_ln58_289_fu_1645_p1) + $signed(sext_ln58_288_fu_1625_p1));

assign add_ln58_671_fu_1655_p2 = ($signed(sext_ln70_2_fu_1178_p1) + $signed(mul_ln73_500_cast_fu_1445_p1));

assign add_ln58_672_fu_1665_p2 = ($signed(sext_ln58_291_fu_1661_p1) + $signed(mul_ln73_482_cast_fu_1094_p1));

assign add_ln58_673_fu_1671_p2 = (zext_ln58_fu_1519_p1 + zext_ln58_473_fu_1527_p1);

assign add_ln58_674_fu_1681_p2 = ($signed(zext_ln58_482_fu_1607_p1) + $signed(12'd3328));

assign add_ln58_675_fu_1691_p2 = ($signed(sext_ln58_292_fu_1687_p1) + $signed(zext_ln58_486_fu_1677_p1));

assign add_ln58_676_fu_1697_p2 = (add_ln58_675_fu_1691_p2 + add_ln58_672_fu_1665_p2);

assign add_ln58_677_fu_1703_p2 = ($signed(mul_ln73_479_cast_fu_1036_p1) + $signed(sext_ln73_2_fu_1200_p1));

assign add_ln58_678_fu_1713_p2 = ($signed(sext_ln58_294_fu_1709_p1) + $signed(mul_ln73_471_cast_fu_910_p1));

assign add_ln58_679_fu_1719_p2 = ($signed(sext_ln73_4_fu_1333_p1) + $signed(sext_ln73_5_fu_1377_p1));

assign add_ln58_680_fu_1729_p2 = ($signed(sext_ln58_296_fu_1725_p1) + $signed(sext_ln58_283_fu_1567_p1));

assign add_ln58_681_fu_1918_p2 = ($signed(sext_ln58_297_fu_1915_p1) + $signed(sext_ln58_295_fu_1912_p1));

assign add_ln58_682_fu_1735_p2 = (zext_ln58_476_fu_1539_p1 + zext_ln58_478_fu_1547_p1);

assign add_ln58_683_fu_1745_p2 = ($signed(zext_ln58_487_fu_1741_p1) + $signed(mul_ln73_501_cast_fu_1467_p1));

assign add_ln58_684_fu_1755_p2 = (zext_ln58_482_fu_1607_p1 + 12'd192);

assign add_ln58_685_fu_1765_p2 = (zext_ln58_488_fu_1761_p1 + zext_ln58_480_fu_1555_p1);

assign add_ln58_686_fu_1775_p2 = ($signed(zext_ln58_489_fu_1771_p1) + $signed(sext_ln58_298_fu_1751_p1));

assign add_ln58_687_fu_1927_p2 = ($signed(sext_ln58_299_fu_1924_p1) + $signed(add_ln58_681_fu_1918_p2));

assign add_ln58_688_fu_1785_p2 = ($signed(mul_ln73_467_cast_fu_838_p1) + $signed(sext_ln70_fu_878_p1));

assign add_ln58_689_fu_1795_p2 = ($signed(sext_ln70_1_fu_932_p1) + $signed(mul_ln73_478_cast_fu_1014_p1));

assign add_ln58_690_fu_1805_p2 = ($signed(sext_ln58_302_fu_1801_p1) + $signed(sext_ln58_301_fu_1791_p1));

assign add_ln58_691_fu_1811_p2 = ($signed(mul_ln73_485_cast_fu_1156_p1) + $signed(sext_ln58_282_fu_1563_p1));

assign add_ln58_692_fu_1821_p2 = ($signed(sext_ln70_4_fu_1307_p1) + $signed(sext_ln58_fu_1515_p1));

assign add_ln58_693_fu_1831_p2 = ($signed(sext_ln58_305_fu_1827_p1) + $signed(sext_ln58_304_fu_1817_p1));

assign add_ln58_694_fu_1943_p2 = ($signed(sext_ln58_306_fu_1940_p1) + $signed(sext_ln58_303_fu_1937_p1));

assign add_ln58_695_fu_1837_p2 = (zext_ln58_475_fu_1535_p1 + zext_ln58_477_fu_1543_p1);

assign add_ln58_696_fu_1847_p2 = (zext_ln58_481_fu_1559_p1 + add_ln73_fu_1349_p2);

assign add_ln58_697_fu_1857_p2 = (zext_ln58_492_fu_1853_p1 + zext_ln58_491_fu_1843_p1);

assign add_ln58_698_fu_1867_p2 = (zext_ln58_483_fu_1611_p1 + zext_ln58_484_fu_1615_p1);

assign add_ln58_699_fu_1877_p2 = ($signed(zext_ln58_490_fu_1781_p1) + $signed(12'd3968));

assign add_ln58_700_fu_1887_p2 = ($signed(sext_ln58_307_fu_1883_p1) + $signed(zext_ln58_494_fu_1873_p1));

assign add_ln58_701_fu_1897_p2 = ($signed(sext_ln58_308_fu_1893_p1) + $signed(zext_ln58_493_fu_1863_p1));

assign add_ln58_702_fu_1949_p2 = (add_ln58_701_reg_2028 + add_ln58_694_fu_1943_p2);

assign add_ln58_fu_1571_p2 = ($signed(sext_ln73_fu_960_p1) + $signed(sext_ln70_3_fu_1266_p1));

assign add_ln73_fu_1349_p2 = (zext_ln73_488_fu_1345_p1 + zext_ln73_299_fu_1311_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = sext_ln58_287_fu_1903_p1;

assign ap_return_1 = sext_ln58_290_fu_1906_p1;

assign ap_return_2 = sext_ln58_293_fu_1909_p1;

assign ap_return_3 = sext_ln58_300_fu_1933_p1;

assign ap_return_4 = sext_ln68_fu_1954_p1;

assign mul_ln73_467_cast_fu_838_p1 = $signed(sub_ln73_366_fu_832_p2);

assign mul_ln73_471_cast_fu_910_p1 = $signed(sub_ln73_370_fu_904_p2);

assign mul_ln73_478_cast_fu_1014_p1 = $signed(sub_ln73_375_fu_1008_p2);

assign mul_ln73_479_cast_fu_1036_p1 = $signed(sub_ln73_376_fu_1030_p2);

assign mul_ln73_482_cast_fu_1094_p1 = $signed(sub_ln73_379_fu_1088_p2);

assign mul_ln73_485_cast_fu_1156_p1 = $signed(sub_ln73_382_fu_1150_p2);

assign mul_ln73_499_cast_fu_1423_p1 = $signed(sub_ln73_394_fu_1417_p2);

assign mul_ln73_500_cast_fu_1445_p1 = $signed(sub_ln73_395_fu_1439_p2);

assign mul_ln73_501_cast_fu_1467_p1 = $signed(sub_ln73_396_fu_1461_p2);

assign mul_ln73_86_fu_270_p0 = zext_ln73_294_fu_936_p1;

assign mul_ln73_86_fu_270_p1 = 11'd27;

assign mul_ln73_87_fu_286_p0 = mul_ln73_87_fu_286_p00;

assign mul_ln73_87_fu_286_p00 = data_22_val;

assign mul_ln73_87_fu_286_p1 = 12'd4077;

assign mul_ln73_fu_299_p0 = zext_ln73_294_fu_936_p1;

assign mul_ln73_fu_299_p1 = 11'd21;

assign p_shl40_fu_1471_p3 = {{data_29_val}, {5'd0}};

assign p_shl45_fu_1391_p3 = {{data_25_val}, {5'd0}};

assign p_shl54_fu_1204_p3 = {{data_19_val}, {4'd0}};

assign p_shl60_fu_1120_p3 = {{data_17_val}, {5'd0}};

assign p_shl61_fu_1102_p3 = {{data_15_val}, {5'd0}};

assign p_shl64_fu_1062_p3 = {{data_13_val}, {5'd0}};

assign p_shl65_fu_1044_p3 = {{data_12_val}, {5'd0}};

assign p_shl79_fu_886_p3 = {{data_4_val}, {5'd0}};

assign p_shl82_fu_846_p3 = {{data_1_val}, {5'd0}};

assign p_shl85_fu_814_p3 = {{data_0_val}, {5'd0}};

assign sext_ln58_282_fu_1563_p1 = sub_ln73_386_fu_1242_p2;

assign sext_ln58_283_fu_1567_p1 = sub_ln73_386_fu_1242_p2;

assign sext_ln58_284_fu_1577_p1 = $signed(add_ln58_fu_1571_p2);

assign sext_ln58_285_fu_1587_p1 = $signed(add_ln58_664_fu_1581_p2);

assign sext_ln58_286_fu_1597_p1 = $signed(add_ln58_665_fu_1591_p2);

assign sext_ln58_287_fu_1903_p1 = $signed(add_ln58_666_reg_1988);

assign sext_ln58_288_fu_1625_p1 = $signed(add_ln58_667_fu_1619_p2);

assign sext_ln58_289_fu_1645_p1 = $signed(add_ln58_669_fu_1639_p2);

assign sext_ln58_290_fu_1906_p1 = $signed(add_ln58_670_reg_1993);

assign sext_ln58_291_fu_1661_p1 = $signed(add_ln58_671_fu_1655_p2);

assign sext_ln58_292_fu_1687_p1 = $signed(add_ln58_674_fu_1681_p2);

assign sext_ln58_293_fu_1909_p1 = $signed(add_ln58_676_reg_1998);

assign sext_ln58_294_fu_1709_p1 = $signed(add_ln58_677_fu_1703_p2);

assign sext_ln58_295_fu_1912_p1 = $signed(add_ln58_678_reg_2003);

assign sext_ln58_296_fu_1725_p1 = $signed(add_ln58_679_fu_1719_p2);

assign sext_ln58_297_fu_1915_p1 = $signed(add_ln58_680_reg_2008);

assign sext_ln58_298_fu_1751_p1 = $signed(add_ln58_683_fu_1745_p2);

assign sext_ln58_299_fu_1924_p1 = $signed(add_ln58_686_reg_2013);

assign sext_ln58_300_fu_1933_p1 = $signed(add_ln58_687_fu_1927_p2);

assign sext_ln58_301_fu_1791_p1 = $signed(add_ln58_688_fu_1785_p2);

assign sext_ln58_302_fu_1801_p1 = $signed(add_ln58_689_fu_1795_p2);

assign sext_ln58_303_fu_1937_p1 = $signed(add_ln58_690_reg_2018);

assign sext_ln58_304_fu_1817_p1 = $signed(add_ln58_691_fu_1811_p2);

assign sext_ln58_305_fu_1827_p1 = $signed(add_ln58_692_fu_1821_p2);

assign sext_ln58_306_fu_1940_p1 = $signed(add_ln58_693_reg_2023);

assign sext_ln58_307_fu_1883_p1 = $signed(add_ln58_699_fu_1877_p2);

assign sext_ln58_308_fu_1893_p1 = $signed(add_ln58_700_fu_1887_p2);

assign sext_ln58_fu_1515_p1 = $signed(sub_ln73_398_fu_1509_p2);

assign sext_ln68_fu_1954_p1 = $signed(add_ln58_702_fu_1949_p2);

assign sext_ln70_1_fu_932_p1 = $signed(sub_ln73_371_fu_926_p2);

assign sext_ln70_2_fu_1178_p1 = $signed(sub_ln73_383_fu_1172_p2);

assign sext_ln70_3_fu_1266_p1 = $signed(sub_ln73_387_fu_1260_p2);

assign sext_ln70_4_fu_1307_p1 = $signed(mul_ln73_87_fu_286_p2);

assign sext_ln70_fu_878_p1 = $signed(sub_ln73_368_fu_872_p2);

assign sext_ln73_1_fu_986_p1 = $signed(sub_ln73_373_fu_980_p2);

assign sext_ln73_2_fu_1200_p1 = $signed(sub_ln73_384_fu_1194_p2);

assign sext_ln73_3_fu_1297_p1 = $signed(sub_ln73_388_fu_1291_p2);

assign sext_ln73_4_fu_1333_p1 = $signed(sub_ln73_390_fu_1327_p2);

assign sext_ln73_5_fu_1377_p1 = $signed(sub_ln73_391_fu_1371_p2);

assign sext_ln73_fu_960_p1 = $signed(sub_ln73_372_fu_954_p2);

assign sub_ln73_366_fu_832_p2 = (12'd0 - zext_ln73_fu_828_p1);

assign sub_ln73_367_fu_854_p2 = (p_shl82_fu_846_p3 - zext_ln70_fu_842_p1);

assign sub_ln73_368_fu_872_p2 = (12'd0 - zext_ln73_471_fu_868_p1);

assign sub_ln73_369_fu_894_p2 = (p_shl79_fu_886_p3 - zext_ln73_293_fu_882_p1);

assign sub_ln73_370_fu_904_p2 = (12'd0 - zext_ln73_472_fu_900_p1);

assign sub_ln73_371_fu_926_p2 = (12'd0 - zext_ln73_473_fu_922_p1);

assign sub_ln73_372_fu_954_p2 = (12'd0 - zext_ln73_474_fu_950_p1);

assign sub_ln73_373_fu_980_p2 = (12'd0 - zext_ln73_475_fu_976_p1);

assign sub_ln73_374_fu_990_p2 = (tmp_930_fu_968_p3 - zext_ln73_295_fu_964_p1);

assign sub_ln73_375_fu_1008_p2 = (12'd0 - zext_ln73_476_fu_1004_p1);

assign sub_ln73_376_fu_1030_p2 = (12'd0 - zext_ln73_477_fu_1026_p1);

assign sub_ln73_377_fu_1052_p2 = (p_shl65_fu_1044_p3 - zext_ln70_3_fu_1040_p1);

assign sub_ln73_378_fu_1070_p2 = (p_shl64_fu_1062_p3 - zext_ln70_4_fu_1058_p1);

assign sub_ln73_379_fu_1088_p2 = (12'd0 - zext_ln73_478_fu_1084_p1);

assign sub_ln73_380_fu_1110_p2 = (p_shl61_fu_1102_p3 - zext_ln70_5_fu_1098_p1);

assign sub_ln73_381_fu_1128_p2 = (p_shl60_fu_1120_p3 - zext_ln73_296_fu_1116_p1);

assign sub_ln73_382_fu_1150_p2 = (zext_ln73_480_fu_1146_p1 - zext_ln73_479_fu_1134_p1);

assign sub_ln73_383_fu_1172_p2 = (12'd0 - zext_ln73_481_fu_1168_p1);

assign sub_ln73_384_fu_1194_p2 = (12'd0 - zext_ln73_482_fu_1190_p1);

assign sub_ln73_385_fu_1224_p2 = (p_shl54_fu_1204_p3 - zext_ln73_483_fu_1220_p1);

assign sub_ln73_386_fu_1242_p2 = (12'd0 - zext_ln73_484_fu_1238_p1);

assign sub_ln73_387_fu_1260_p2 = (12'd0 - zext_ln73_485_fu_1256_p1);

assign sub_ln73_388_fu_1291_p2 = (12'd0 - zext_ln73_486_fu_1287_p1);

assign sub_ln73_389_fu_1301_p2 = (tmp_940_fu_1279_p3 - zext_ln73_298_fu_1275_p1);

assign sub_ln73_390_fu_1327_p2 = (12'd0 - zext_ln73_487_fu_1323_p1);

assign sub_ln73_391_fu_1371_p2 = (12'd0 - zext_ln73_489_fu_1367_p1);

assign sub_ln73_392_fu_1381_p2 = (tmp_943_fu_1359_p3 - zext_ln73_300_fu_1355_p1);

assign sub_ln73_393_fu_1399_p2 = (p_shl45_fu_1391_p3 - zext_ln70_6_fu_1387_p1);

assign sub_ln73_394_fu_1417_p2 = (12'd0 - zext_ln73_490_fu_1413_p1);

assign sub_ln73_395_fu_1439_p2 = (12'd0 - zext_ln73_491_fu_1435_p1);

assign sub_ln73_396_fu_1461_p2 = (12'd0 - zext_ln73_492_fu_1457_p1);

assign sub_ln73_397_fu_1491_p2 = (p_shl40_fu_1471_p3 - zext_ln73_493_fu_1487_p1);

assign sub_ln73_398_fu_1509_p2 = (12'd0 - zext_ln73_494_fu_1505_p1);

assign sub_ln73_fu_822_p2 = (p_shl85_fu_814_p3 - zext_ln73_292_fu_810_p1);

assign tmp_928_fu_914_p3 = {{data_5_val}, {5'd0}};

assign tmp_929_fu_942_p3 = {{data_6_val}, {5'd0}};

assign tmp_930_fu_968_p3 = {{data_7_val}, {5'd0}};

assign tmp_931_fu_996_p3 = {{data_9_val}, {5'd0}};

assign tmp_932_fu_1018_p3 = {{data_11_val}, {5'd0}};

assign tmp_933_fu_1076_p3 = {{data_14_val}, {5'd0}};

assign tmp_934_fu_1138_p3 = {{data_17_val}, {1'd0}};

assign tmp_935_fu_1160_p3 = {{data_18_val}, {5'd0}};

assign tmp_936_fu_1182_p3 = {{data_19_val}, {5'd0}};

assign tmp_937_fu_1212_p3 = {{data_19_val}, {2'd0}};

assign tmp_938_fu_1230_p3 = {{data_20_val}, {5'd0}};

assign tmp_939_fu_1248_p3 = {{data_21_val}, {5'd0}};

assign tmp_940_fu_1279_p3 = {{data_22_val}, {5'd0}};

assign tmp_941_fu_1315_p3 = {{data_23_val}, {5'd0}};

assign tmp_942_fu_1337_p3 = {{data_23_val}, {4'd0}};

assign tmp_943_fu_1359_p3 = {{data_24_val}, {5'd0}};

assign tmp_944_fu_1405_p3 = {{data_26_val}, {5'd0}};

assign tmp_945_fu_1427_p3 = {{data_27_val}, {5'd0}};

assign tmp_946_fu_1449_p3 = {{data_28_val}, {5'd0}};

assign tmp_947_fu_1479_p3 = {{data_29_val}, {1'd0}};

assign tmp_948_fu_1497_p3 = {{data_31_val}, {5'd0}};

assign tmp_fu_860_p3 = {{data_3_val}, {5'd0}};

assign zext_ln58_472_fu_1523_p1 = sub_ln73_367_fu_854_p2;

assign zext_ln58_473_fu_1527_p1 = sub_ln73_369_fu_894_p2;

assign zext_ln58_474_fu_1531_p1 = mul_ln73_fu_299_p2;

assign zext_ln58_475_fu_1535_p1 = mul_ln73_86_fu_270_p2;

assign zext_ln58_476_fu_1539_p1 = sub_ln73_374_fu_990_p2;

assign zext_ln58_477_fu_1543_p1 = sub_ln73_377_fu_1052_p2;

assign zext_ln58_478_fu_1547_p1 = sub_ln73_378_fu_1070_p2;

assign zext_ln58_479_fu_1551_p1 = sub_ln73_380_fu_1110_p2;

assign zext_ln58_480_fu_1555_p1 = sub_ln73_381_fu_1128_p2;

assign zext_ln58_481_fu_1559_p1 = sub_ln73_385_fu_1224_p2;

assign zext_ln58_482_fu_1607_p1 = sub_ln73_389_fu_1301_p2;

assign zext_ln58_483_fu_1611_p1 = sub_ln73_392_fu_1381_p2;

assign zext_ln58_484_fu_1615_p1 = sub_ln73_393_fu_1399_p2;

assign zext_ln58_485_fu_1635_p1 = add_ln58_668_fu_1629_p2;

assign zext_ln58_486_fu_1677_p1 = add_ln58_673_fu_1671_p2;

assign zext_ln58_487_fu_1741_p1 = add_ln58_682_fu_1735_p2;

assign zext_ln58_488_fu_1761_p1 = add_ln58_684_fu_1755_p2;

assign zext_ln58_489_fu_1771_p1 = add_ln58_685_fu_1765_p2;

assign zext_ln58_490_fu_1781_p1 = sub_ln73_397_fu_1491_p2;

assign zext_ln58_491_fu_1843_p1 = add_ln58_695_fu_1837_p2;

assign zext_ln58_492_fu_1853_p1 = add_ln58_696_fu_1847_p2;

assign zext_ln58_493_fu_1863_p1 = add_ln58_697_fu_1857_p2;

assign zext_ln58_494_fu_1873_p1 = add_ln58_698_fu_1867_p2;

assign zext_ln58_fu_1519_p1 = sub_ln73_fu_822_p2;

assign zext_ln70_3_fu_1040_p1 = data_12_val;

assign zext_ln70_4_fu_1058_p1 = data_13_val;

assign zext_ln70_5_fu_1098_p1 = data_15_val;

assign zext_ln70_6_fu_1387_p1 = data_25_val;

assign zext_ln70_fu_842_p1 = data_1_val;

assign zext_ln73_292_fu_810_p1 = data_0_val;

assign zext_ln73_293_fu_882_p1 = data_4_val;

assign zext_ln73_294_fu_936_p1 = data_6_val;

assign zext_ln73_295_fu_964_p1 = data_7_val;

assign zext_ln73_296_fu_1116_p1 = data_17_val;

assign zext_ln73_298_fu_1275_p1 = data_22_val;

assign zext_ln73_299_fu_1311_p1 = data_23_val;

assign zext_ln73_300_fu_1355_p1 = data_24_val;

assign zext_ln73_471_fu_868_p1 = tmp_fu_860_p3;

assign zext_ln73_472_fu_900_p1 = p_shl79_fu_886_p3;

assign zext_ln73_473_fu_922_p1 = tmp_928_fu_914_p3;

assign zext_ln73_474_fu_950_p1 = tmp_929_fu_942_p3;

assign zext_ln73_475_fu_976_p1 = tmp_930_fu_968_p3;

assign zext_ln73_476_fu_1004_p1 = tmp_931_fu_996_p3;

assign zext_ln73_477_fu_1026_p1 = tmp_932_fu_1018_p3;

assign zext_ln73_478_fu_1084_p1 = tmp_933_fu_1076_p3;

assign zext_ln73_479_fu_1134_p1 = p_shl60_fu_1120_p3;

assign zext_ln73_480_fu_1146_p1 = tmp_934_fu_1138_p3;

assign zext_ln73_481_fu_1168_p1 = tmp_935_fu_1160_p3;

assign zext_ln73_482_fu_1190_p1 = tmp_936_fu_1182_p3;

assign zext_ln73_483_fu_1220_p1 = tmp_937_fu_1212_p3;

assign zext_ln73_484_fu_1238_p1 = tmp_938_fu_1230_p3;

assign zext_ln73_485_fu_1256_p1 = tmp_939_fu_1248_p3;

assign zext_ln73_486_fu_1287_p1 = tmp_940_fu_1279_p3;

assign zext_ln73_487_fu_1323_p1 = tmp_941_fu_1315_p3;

assign zext_ln73_488_fu_1345_p1 = tmp_942_fu_1337_p3;

assign zext_ln73_489_fu_1367_p1 = tmp_943_fu_1359_p3;

assign zext_ln73_490_fu_1413_p1 = tmp_944_fu_1405_p3;

assign zext_ln73_491_fu_1435_p1 = tmp_945_fu_1427_p3;

assign zext_ln73_492_fu_1457_p1 = tmp_946_fu_1449_p3;

assign zext_ln73_493_fu_1487_p1 = tmp_947_fu_1479_p3;

assign zext_ln73_494_fu_1505_p1 = tmp_948_fu_1497_p3;

assign zext_ln73_fu_828_p1 = p_shl85_fu_814_p3;

always @ (posedge ap_clk) begin
    add_ln58_678_reg_2003[4:0] <= 5'b00000;
    add_ln58_680_reg_2008[4:0] <= 5'b00000;
    add_ln58_690_reg_2018[4:0] <= 5'b00000;
end

endmodule //myproject_dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_18_7_5_3_0_config11_s
