// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_myproject,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.615000,HLS_SYN_LAT=8,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3055,HLS_SYN_LUT=26092,HLS_VERSION=2023_2}" *)

module myproject (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_1_ap_vld,
        input_1,
        layer20_out_0,
        layer20_out_0_ap_vld,
        layer20_out_1,
        layer20_out_1_ap_vld,
        layer20_out_2,
        layer20_out_2_ap_vld,
        layer20_out_3,
        layer20_out_3_ap_vld,
        layer20_out_4,
        layer20_out_4_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   input_1_ap_vld;
input  [255:0] input_1;
output  [15:0] layer20_out_0;
output   layer20_out_0_ap_vld;
output  [15:0] layer20_out_1;
output   layer20_out_1_ap_vld;
output  [15:0] layer20_out_2;
output   layer20_out_2_ap_vld;
output  [15:0] layer20_out_3;
output   layer20_out_3_ap_vld;
output  [15:0] layer20_out_4;
output   layer20_out_4_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer20_out_0_ap_vld;
reg layer20_out_1_ap_vld;
reg layer20_out_2_ap_vld;
reg layer20_out_3_ap_vld;
reg layer20_out_4_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
reg    input_1_ap_vld_in_sig;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg   [255:0] input_1_preg;
reg   [255:0] input_1_in_sig;
reg    input_1_ap_vld_preg;
reg    input_1_blk_n;
wire    ap_block_pp0_stage0;
wire   [7:0] add_ln30_fu_479_p2;
reg   [7:0] add_ln30_reg_2653;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] add_ln31_fu_507_p2;
reg   [7:0] add_ln31_reg_2658;
wire   [9:0] add_ln32_fu_535_p2;
reg   [9:0] add_ln32_reg_2663;
wire   [9:0] add_ln33_fu_563_p2;
reg   [9:0] add_ln33_reg_2668;
wire   [9:0] add_ln34_fu_591_p2;
reg   [9:0] add_ln34_reg_2673;
wire   [8:0] add_ln35_fu_619_p2;
reg   [8:0] add_ln35_reg_2678;
wire   [4:0] add_ln36_fu_647_p2;
reg   [4:0] add_ln36_reg_2683;
wire   [6:0] add_ln37_fu_675_p2;
reg   [6:0] add_ln37_reg_2688;
wire   [4:0] add_ln38_fu_703_p2;
reg   [4:0] add_ln38_reg_2693;
wire   [6:0] add_ln39_fu_731_p2;
reg   [6:0] add_ln39_reg_2698;
wire   [5:0] add_ln40_fu_759_p2;
reg   [5:0] add_ln40_reg_2703;
wire   [6:0] add_ln41_fu_787_p2;
reg   [6:0] add_ln41_reg_2708;
wire   [6:0] add_ln42_fu_815_p2;
reg   [6:0] add_ln42_reg_2713;
wire   [4:0] add_ln43_fu_843_p2;
reg   [4:0] add_ln43_reg_2718;
wire   [11:0] add_ln44_fu_871_p2;
reg   [11:0] add_ln44_reg_2723;
wire   [7:0] add_ln45_fu_899_p2;
reg   [7:0] add_ln45_reg_2728;
reg   [3:0] tmp_reg_2733;
reg   [7:0] tmp_1_reg_2738;
reg   [9:0] tmp_2_reg_2743;
reg   [4:0] tmp_3_reg_2748;
reg   [3:0] tmp_4_reg_2753;
reg   [10:0] tmp_5_reg_2758;
reg   [7:0] tmp_6_reg_2763;
reg   [6:0] tmp_7_reg_2768;
reg   [5:0] tmp_8_reg_2773;
reg   [6:0] tmp_9_reg_2778;
reg   [7:0] tmp_s_reg_2783;
reg   [5:0] tmp_10_reg_2788;
reg   [6:0] tmp_11_reg_2793;
reg   [5:0] tmp_12_reg_2798;
reg   [5:0] tmp_13_reg_2803;
reg   [4:0] tmp_14_reg_2808;
reg   [5:0] tmp_15_reg_2813;
reg   [5:0] tmp_16_reg_2818;
reg   [5:0] tmp_17_reg_2823;
reg   [8:0] tmp_18_reg_2828;
reg   [4:0] tmp_19_reg_2833;
reg   [6:0] tmp_20_reg_2838;
reg   [4:0] tmp_21_reg_2843;
reg   [3:0] tmp_22_reg_2848;
reg   [4:0] tmp_23_reg_2853;
reg   [5:0] tmp_24_reg_2858;
reg   [4:0] tmp_25_reg_2863;
reg   [3:0] tmp_26_reg_2868;
reg   [5:0] tmp_27_reg_2873;
reg   [3:0] tmp_28_reg_2878;
reg   [5:0] tmp_29_reg_2883;
reg   [6:0] tmp_30_reg_2888;
reg   [5:0] tmp_31_reg_2893;
reg   [5:0] tmp_32_reg_2898;
reg   [5:0] tmp_33_reg_2903;
reg   [7:0] tmp_34_reg_2908;
reg   [7:0] tmp_35_reg_2913;
reg   [4:0] tmp_36_reg_2918;
reg   [6:0] tmp_37_reg_2923;
reg   [6:0] tmp_38_reg_2928;
reg   [4:0] tmp_39_reg_2933;
reg   [6:0] tmp_40_reg_2938;
reg   [3:0] tmp_41_reg_2943;
reg   [4:0] tmp_42_reg_2948;
reg   [6:0] tmp_43_reg_2953;
reg   [5:0] tmp_44_reg_2958;
reg   [5:0] tmp_45_reg_2963;
reg   [3:0] tmp_46_reg_2968;
reg   [4:0] tmp_47_reg_2973;
reg   [6:0] tmp_48_reg_2978;
reg   [3:0] tmp_49_reg_2983;
reg   [4:0] tmp_50_reg_2988;
reg   [5:0] tmp_51_reg_2993;
reg   [5:0] tmp_52_reg_2998;
reg   [6:0] tmp_53_reg_3003;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_0_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_1_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_2_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_3_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_4_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_5_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_6_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_7_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_8_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_9_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_10_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_11_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_12_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_13_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_14_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_15_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_0;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_1;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_2;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_3;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_4;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_5;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_6;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_7;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_8;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_9;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_10;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_11;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_12;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_13;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_14;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_15;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_16;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_17;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_18;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_19;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_20;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_21;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_22;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_23;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_24;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_25;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_26;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_27;
reg    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call95;
reg    ap_block_pp0_stage0_11001_ignoreCallOp91;
wire    call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_ready;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_0;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_1;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_2;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_3;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_4;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_5;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_6;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_7;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_8;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_9;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_10;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_11;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_12;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_13;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_14;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_15;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_16;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_17;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_18;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_19;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_20;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_21;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_22;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_23;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_24;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_25;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_26;
wire   [15:0] call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_27;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_0_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_1_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_4_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_5_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_7_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_8_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_9_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_16_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_17_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_20_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_25_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_29_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_30_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_31_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_35_val;
wire   [11:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_36_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_46_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_47_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_48_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_49_val;
wire   [11:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_51_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_52_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_54_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_55_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_56_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_58_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_59_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_60_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_0;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_1;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_2;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_3;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_4;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_5;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_6;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_7;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_8;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_9;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_10;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_11;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_12;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_13;
reg    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call209;
reg    ap_block_pp0_stage0_11001_ignoreCallOp206;
wire    call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_ready;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_0;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_1;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_2;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_3;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_4;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_5;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_6;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_7;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_8;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_9;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_10;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_11;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_12;
wire   [15:0] call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_13;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_1_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_2_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_4_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_5_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_6_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_7_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_8_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_11_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_13_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_19_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_20_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_21_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_26_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_31_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_0;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_1;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_2;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_3;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_4;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_5;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_6;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_7;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_8;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_9;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_10;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_11;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_12;
reg    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call267;
reg    ap_block_pp0_stage0_11001_ignoreCallOp265;
wire    call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_ready;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_0;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_1;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_2;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_3;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_4;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_5;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_6;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_7;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_8;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_9;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_10;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_11;
wire   [15:0] call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_12;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_1_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_2_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_3_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_4_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_5_val;
wire   [12:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_7_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_9_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_14_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_22_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_24_val;
wire   [13:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_25_val;
wire   [14:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_28_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_29_val;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_0;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_1;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_2;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_3;
wire   [15:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_4;
reg    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call321;
reg    ap_block_pp0_stage0_11001_ignoreCallOp320;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_60_fu_467_p3;
wire   [7:0] zext_ln30_fu_475_p1;
wire   [7:0] trunc_ln30_1_fu_457_p4;
wire   [0:0] tmp_61_fu_495_p3;
wire   [7:0] zext_ln31_fu_503_p1;
wire   [7:0] trunc_ln_fu_485_p4;
wire   [0:0] tmp_62_fu_523_p3;
wire   [9:0] zext_ln32_fu_531_p1;
wire   [9:0] trunc_ln1_fu_513_p4;
wire   [0:0] tmp_63_fu_551_p3;
wire   [9:0] zext_ln33_fu_559_p1;
wire   [9:0] trunc_ln2_fu_541_p4;
wire   [0:0] tmp_64_fu_579_p3;
wire   [9:0] zext_ln34_fu_587_p1;
wire   [9:0] trunc_ln3_fu_569_p4;
wire   [0:0] tmp_65_fu_607_p3;
wire   [8:0] zext_ln35_fu_615_p1;
wire   [8:0] trunc_ln4_fu_597_p4;
wire   [0:0] tmp_66_fu_635_p3;
wire   [4:0] zext_ln36_fu_643_p1;
wire   [4:0] trunc_ln5_fu_625_p4;
wire   [0:0] tmp_67_fu_663_p3;
wire   [6:0] zext_ln37_fu_671_p1;
wire   [6:0] trunc_ln6_fu_653_p4;
wire   [0:0] tmp_68_fu_691_p3;
wire   [4:0] zext_ln38_fu_699_p1;
wire   [4:0] trunc_ln7_fu_681_p4;
wire   [0:0] tmp_69_fu_719_p3;
wire   [6:0] zext_ln39_fu_727_p1;
wire   [6:0] trunc_ln8_fu_709_p4;
wire   [0:0] tmp_70_fu_747_p3;
wire   [5:0] zext_ln40_fu_755_p1;
wire   [5:0] trunc_ln9_fu_737_p4;
wire   [0:0] tmp_71_fu_775_p3;
wire   [6:0] zext_ln41_fu_783_p1;
wire   [6:0] trunc_ln10_fu_765_p4;
wire   [0:0] tmp_72_fu_803_p3;
wire   [6:0] zext_ln42_fu_811_p1;
wire   [6:0] trunc_ln11_fu_793_p4;
wire   [0:0] tmp_73_fu_831_p3;
wire   [4:0] zext_ln43_fu_839_p1;
wire   [4:0] trunc_ln12_fu_821_p4;
wire   [0:0] tmp_74_fu_859_p3;
wire   [11:0] zext_ln44_fu_867_p1;
wire   [11:0] trunc_ln13_fu_849_p4;
wire   [0:0] tmp_75_fu_887_p3;
wire   [7:0] zext_ln45_fu_895_p1;
wire   [7:0] trunc_ln14_fu_877_p4;
wire   [9:0] tmp_54_fu_2538_p4;
wire   [14:0] shl_ln_fu_2548_p3;
wire   [10:0] tmp_55_fu_2561_p4;
wire   [14:0] shl_ln1_fu_2571_p3;
wire   [9:0] tmp_56_fu_2584_p4;
wire   [14:0] shl_ln2_fu_2594_p3;
wire   [10:0] tmp_57_fu_2607_p4;
wire   [14:0] shl_ln3_fu_2617_p3;
wire   [9:0] tmp_58_fu_2630_p4;
wire   [14:0] shl_ln4_fu_2640_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to7;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 input_1_preg = 256'd0;
#0 input_1_ap_vld_preg = 1'b0;
end

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_0_val),
    .data_1_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_1_val),
    .data_2_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_2_val),
    .data_3_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_3_val),
    .data_4_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_4_val),
    .data_5_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_5_val),
    .data_6_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_6_val),
    .data_7_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_7_val),
    .data_8_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_8_val),
    .data_9_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_9_val),
    .data_10_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_10_val),
    .data_11_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_11_val),
    .data_12_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_12_val),
    .data_13_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_13_val),
    .data_14_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_14_val),
    .data_15_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_15_val),
    .ap_return_0(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_7),
    .ap_return_8(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_8),
    .ap_return_9(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_9),
    .ap_return_10(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_10),
    .ap_return_11(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_11),
    .ap_return_12(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_12),
    .ap_return_13(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_13),
    .ap_return_14(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_14),
    .ap_return_15(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_15),
    .ap_return_16(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_16),
    .ap_return_17(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_17),
    .ap_return_18(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_18),
    .ap_return_19(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_19),
    .ap_return_20(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_20),
    .ap_return_21(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_21),
    .ap_return_22(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_22),
    .ap_return_23(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_23),
    .ap_return_24(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_24),
    .ap_return_25(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_25),
    .ap_return_26(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_26),
    .ap_return_27(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_27),
    .ap_ce(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_ce)
);

myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323(
    .ap_ready(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_ready),
    .data_0_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_0),
    .data_1_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_1),
    .data_4_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_2),
    .data_5_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_3),
    .data_7_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_4),
    .data_8_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_5),
    .data_9_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_6),
    .data_16_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_7),
    .data_17_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_8),
    .data_20_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_9),
    .data_25_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_10),
    .data_29_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_11),
    .data_30_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_12),
    .data_31_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_13),
    .data_35_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_14),
    .data_36_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_15),
    .data_46_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_16),
    .data_47_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_17),
    .data_48_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_18),
    .data_49_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_19),
    .data_51_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_20),
    .data_52_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_21),
    .data_54_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_22),
    .data_55_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_23),
    .data_56_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_24),
    .data_58_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_25),
    .data_59_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_26),
    .data_60_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_return_27),
    .ap_return_0(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_0),
    .ap_return_1(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_1),
    .ap_return_2(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_2),
    .ap_return_3(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_3),
    .ap_return_4(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_4),
    .ap_return_5(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_5),
    .ap_return_6(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_6),
    .ap_return_7(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_7),
    .ap_return_8(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_8),
    .ap_return_9(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_9),
    .ap_return_10(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_10),
    .ap_return_11(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_11),
    .ap_return_12(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_12),
    .ap_return_13(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_13),
    .ap_return_14(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_14),
    .ap_return_15(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_15),
    .ap_return_16(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_16),
    .ap_return_17(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_17),
    .ap_return_18(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_18),
    .ap_return_19(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_19),
    .ap_return_20(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_20),
    .ap_return_21(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_21),
    .ap_return_22(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_22),
    .ap_return_23(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_23),
    .ap_return_24(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_24),
    .ap_return_25(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_25),
    .ap_return_26(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_26),
    .ap_return_27(call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_27)
);

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_0_val),
    .data_1_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_1_val),
    .data_4_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_4_val),
    .data_5_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_5_val),
    .data_7_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_7_val),
    .data_8_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_8_val),
    .data_9_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_9_val),
    .data_16_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_16_val),
    .data_17_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_17_val),
    .data_20_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_20_val),
    .data_25_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_25_val),
    .data_29_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_29_val),
    .data_30_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_30_val),
    .data_31_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_31_val),
    .data_35_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_35_val),
    .data_36_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_36_val),
    .data_46_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_46_val),
    .data_47_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_47_val),
    .data_48_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_48_val),
    .data_49_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_49_val),
    .data_51_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_51_val),
    .data_52_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_52_val),
    .data_54_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_54_val),
    .data_55_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_55_val),
    .data_56_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_56_val),
    .data_58_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_58_val),
    .data_59_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_59_val),
    .data_60_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_60_val),
    .ap_return_0(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_7),
    .ap_return_8(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_8),
    .ap_return_9(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_9),
    .ap_return_10(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_10),
    .ap_return_11(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_11),
    .ap_return_12(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_12),
    .ap_return_13(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_13),
    .ap_ce(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_ce)
);

myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387(
    .ap_ready(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_ready),
    .data_1_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_0),
    .data_2_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_1),
    .data_4_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_2),
    .data_5_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_3),
    .data_6_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_4),
    .data_7_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_5),
    .data_8_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_6),
    .data_11_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_7),
    .data_13_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_8),
    .data_19_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_9),
    .data_20_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_10),
    .data_21_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_11),
    .data_26_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_12),
    .data_31_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_return_13),
    .ap_return_0(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_0),
    .ap_return_1(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_1),
    .ap_return_2(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_2),
    .ap_return_3(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_3),
    .ap_return_4(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_4),
    .ap_return_5(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_5),
    .ap_return_6(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_6),
    .ap_return_7(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_7),
    .ap_return_8(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_8),
    .ap_return_9(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_9),
    .ap_return_10(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_10),
    .ap_return_11(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_11),
    .ap_return_12(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_12),
    .ap_return_13(call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_13)
);

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_1_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_1_val),
    .data_2_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_2_val),
    .data_4_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_4_val),
    .data_5_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_5_val),
    .data_6_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_6_val),
    .data_7_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_7_val),
    .data_8_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_8_val),
    .data_11_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_11_val),
    .data_13_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_13_val),
    .data_19_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_19_val),
    .data_20_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_20_val),
    .data_21_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_21_val),
    .data_26_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_26_val),
    .data_31_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_31_val),
    .ap_return_0(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_7),
    .ap_return_8(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_8),
    .ap_return_9(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_9),
    .ap_return_10(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_10),
    .ap_return_11(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_11),
    .ap_return_12(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_12),
    .ap_ce(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_ce)
);

myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423(
    .ap_ready(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_ready),
    .data_1_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_0),
    .data_2_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_1),
    .data_3_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_2),
    .data_4_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_3),
    .data_5_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_4),
    .data_7_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_5),
    .data_9_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_6),
    .data_14_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_7),
    .data_22_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_8),
    .data_24_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_9),
    .data_25_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_10),
    .data_28_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_11),
    .data_29_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_return_12),
    .ap_return_0(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_0),
    .ap_return_1(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_1),
    .ap_return_2(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_2),
    .ap_return_3(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_3),
    .ap_return_4(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_4),
    .ap_return_5(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_5),
    .ap_return_6(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_6),
    .ap_return_7(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_7),
    .ap_return_8(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_8),
    .ap_return_9(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_9),
    .ap_return_10(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_10),
    .ap_return_11(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_11),
    .ap_return_12(call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_12)
);

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_1_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_1_val),
    .data_2_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_2_val),
    .data_3_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_3_val),
    .data_4_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_4_val),
    .data_5_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_5_val),
    .data_7_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_7_val),
    .data_9_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_9_val),
    .data_14_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_14_val),
    .data_22_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_22_val),
    .data_24_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_24_val),
    .data_25_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_25_val),
    .data_28_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_28_val),
    .data_29_val(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_29_val),
    .ap_return_0(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_4),
    .ap_ce(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_1_ap_vld_preg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            input_1_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (input_1_ap_vld == 1'b1))) begin
            input_1_ap_vld_preg <= input_1_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_1_preg <= 256'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (input_1_ap_vld == 1'b1))) begin
            input_1_preg <= input_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln30_reg_2653 <= add_ln30_fu_479_p2;
        add_ln31_reg_2658 <= add_ln31_fu_507_p2;
        add_ln32_reg_2663 <= add_ln32_fu_535_p2;
        add_ln33_reg_2668 <= add_ln33_fu_563_p2;
        add_ln34_reg_2673 <= add_ln34_fu_591_p2;
        add_ln35_reg_2678 <= add_ln35_fu_619_p2;
        add_ln36_reg_2683 <= add_ln36_fu_647_p2;
        add_ln37_reg_2688 <= add_ln37_fu_675_p2;
        add_ln38_reg_2693 <= add_ln38_fu_703_p2;
        add_ln39_reg_2698 <= add_ln39_fu_731_p2;
        add_ln40_reg_2703 <= add_ln40_fu_759_p2;
        add_ln41_reg_2708 <= add_ln41_fu_787_p2;
        add_ln42_reg_2713 <= add_ln42_fu_815_p2;
        add_ln43_reg_2718 <= add_ln43_fu_843_p2;
        add_ln44_reg_2723 <= add_ln44_fu_871_p2;
        add_ln45_reg_2728 <= add_ln45_fu_899_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp_10_reg_2788 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_11[13:8]}};
        tmp_11_reg_2793 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_12[14:8]}};
        tmp_12_reg_2798 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_13[13:8]}};
        tmp_13_reg_2803 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_14[13:8]}};
        tmp_14_reg_2808 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_15[11:7]}};
        tmp_15_reg_2813 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_16[13:8]}};
        tmp_16_reg_2818 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_17[14:9]}};
        tmp_17_reg_2823 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_18[14:9]}};
        tmp_18_reg_2828 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_19[13:5]}};
        tmp_19_reg_2833 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_20[11:7]}};
        tmp_1_reg_2738 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_1[13:6]}};
        tmp_20_reg_2838 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_21[13:7]}};
        tmp_21_reg_2843 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_22[12:8]}};
        tmp_22_reg_2848 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_23[12:9]}};
        tmp_23_reg_2853 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_24[13:9]}};
        tmp_24_reg_2858 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_25[13:8]}};
        tmp_25_reg_2863 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_26[13:9]}};
        tmp_26_reg_2868 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_27[13:10]}};
        tmp_27_reg_2873 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_0[15:10]}};
        tmp_28_reg_2878 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_1[13:10]}};
        tmp_29_reg_2883 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_2[13:8]}};
        tmp_2_reg_2743 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_2[15:6]}};
        tmp_30_reg_2888 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_3[15:9]}};
        tmp_31_reg_2893 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_4[15:10]}};
        tmp_32_reg_2898 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_5[13:8]}};
        tmp_33_reg_2903 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_6[15:10]}};
        tmp_34_reg_2908 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_7[15:8]}};
        tmp_35_reg_2913 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_8[15:8]}};
        tmp_36_reg_2918 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_9[13:9]}};
        tmp_37_reg_2923 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_10[14:8]}};
        tmp_38_reg_2928 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_11[15:9]}};
        tmp_39_reg_2933 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_12[14:10]}};
        tmp_3_reg_2748 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_3[12:8]}};
        tmp_40_reg_2938 <= {{call_ret3_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config11_s_fu_387_ap_return_13[14:8]}};
        tmp_41_reg_2943 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_0[12:9]}};
        tmp_42_reg_2948 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_1[12:8]}};
        tmp_43_reg_2953 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_2[14:8]}};
        tmp_44_reg_2958 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_3[14:9]}};
        tmp_45_reg_2963 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_4[13:8]}};
        tmp_46_reg_2968 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_5[12:9]}};
        tmp_47_reg_2973 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_6[13:9]}};
        tmp_48_reg_2978 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_7[14:8]}};
        tmp_49_reg_2983 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_8[13:10]}};
        tmp_4_reg_2753 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_4[12:9]}};
        tmp_50_reg_2988 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_9[14:10]}};
        tmp_51_reg_2993 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_10[13:8]}};
        tmp_52_reg_2998 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_11[14:9]}};
        tmp_53_reg_3003 <= {{call_ret5_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config16_s_fu_423_ap_return_12[15:9]}};
        tmp_5_reg_2758 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_5[15:5]}};
        tmp_6_reg_2763 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_6[13:6]}};
        tmp_7_reg_2768 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_7[13:7]}};
        tmp_8_reg_2773 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_8[12:7]}};
        tmp_9_reg_2778 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_9[13:7]}};
        tmp_reg_2733 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_0[12:9]}};
        tmp_s_reg_2783 <= {{call_ret_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_ReLU_config6_s_fu_323_ap_return_10[14:7]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to7 = 1'b1;
    end else begin
        ap_idle_pp0_0to7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to7 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp265) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp320) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp91) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp206) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((input_1_ap_vld == 1'b1)) begin
        input_1_ap_vld_in_sig = input_1_ap_vld;
    end else begin
        input_1_ap_vld_in_sig = input_1_ap_vld_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_1_blk_n = input_1_ap_vld;
    end else begin
        input_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((input_1_ap_vld == 1'b1)) begin
        input_1_in_sig = input_1;
    end else begin
        input_1_in_sig = input_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        layer20_out_0_ap_vld = 1'b1;
    end else begin
        layer20_out_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        layer20_out_1_ap_vld = 1'b1;
    end else begin
        layer20_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        layer20_out_2_ap_vld = 1'b1;
    end else begin
        layer20_out_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        layer20_out_3_ap_vld = 1'b1;
    end else begin
        layer20_out_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        layer20_out_4_ap_vld = 1'b1;
    end else begin
        layer20_out_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln30_fu_479_p2 = (zext_ln30_fu_475_p1 + trunc_ln30_1_fu_457_p4);

assign add_ln31_fu_507_p2 = (zext_ln31_fu_503_p1 + trunc_ln_fu_485_p4);

assign add_ln32_fu_535_p2 = (zext_ln32_fu_531_p1 + trunc_ln1_fu_513_p4);

assign add_ln33_fu_563_p2 = (zext_ln33_fu_559_p1 + trunc_ln2_fu_541_p4);

assign add_ln34_fu_591_p2 = (zext_ln34_fu_587_p1 + trunc_ln3_fu_569_p4);

assign add_ln35_fu_619_p2 = (zext_ln35_fu_615_p1 + trunc_ln4_fu_597_p4);

assign add_ln36_fu_647_p2 = (zext_ln36_fu_643_p1 + trunc_ln5_fu_625_p4);

assign add_ln37_fu_675_p2 = (zext_ln37_fu_671_p1 + trunc_ln6_fu_653_p4);

assign add_ln38_fu_703_p2 = (zext_ln38_fu_699_p1 + trunc_ln7_fu_681_p4);

assign add_ln39_fu_731_p2 = (zext_ln39_fu_727_p1 + trunc_ln8_fu_709_p4);

assign add_ln40_fu_759_p2 = (zext_ln40_fu_755_p1 + trunc_ln9_fu_737_p4);

assign add_ln41_fu_787_p2 = (zext_ln41_fu_783_p1 + trunc_ln10_fu_765_p4);

assign add_ln42_fu_815_p2 = (zext_ln42_fu_811_p1 + trunc_ln11_fu_793_p4);

assign add_ln43_fu_843_p2 = (zext_ln43_fu_839_p1 + trunc_ln12_fu_821_p4);

assign add_ln44_fu_871_p2 = (zext_ln44_fu_867_p1 + trunc_ln13_fu_849_p4);

assign add_ln45_fu_899_p2 = (zext_ln45_fu_895_p1 + trunc_ln14_fu_877_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp206 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call209));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp265 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call267));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp320 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call321));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp91 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call95));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (input_1_ap_vld_in_sig == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call209 = (input_1_ap_vld_in_sig == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call267 = (input_1_ap_vld_in_sig == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call321 = (input_1_ap_vld_in_sig == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call95 = (input_1_ap_vld_in_sig == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_11_val = {{tmp_34_reg_2908}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_13_val = {{tmp_35_reg_2913}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_19_val = {{tmp_36_reg_2918}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_1_val = {{tmp_27_reg_2873}, {10'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_20_val = {{tmp_37_reg_2923}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_21_val = {{tmp_38_reg_2928}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_26_val = {{tmp_39_reg_2933}, {10'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_2_val = {{tmp_28_reg_2878}, {10'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_31_val = {{tmp_40_reg_2938}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_4_val = {{tmp_29_reg_2883}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_5_val = {{tmp_30_reg_2888}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_6_val = {{tmp_31_reg_2893}, {10'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_7_val = {{tmp_32_reg_2898}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config13_s_fu_405_data_8_val = {{tmp_33_reg_2903}, {10'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_14_val = {{tmp_48_reg_2978}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_1_val = {{tmp_41_reg_2943}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_22_val = {{tmp_49_reg_2983}, {10'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_24_val = {{tmp_50_reg_2988}, {10'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_25_val = {{tmp_51_reg_2993}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_28_val = {{tmp_52_reg_2998}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_29_val = {{tmp_53_reg_3003}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_2_val = {{tmp_42_reg_2948}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_3_val = {{tmp_43_reg_2953}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_4_val = {{tmp_44_reg_2958}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_5_val = {{tmp_45_reg_2963}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_7_val = {{tmp_46_reg_2968}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_data_9_val = {{tmp_47_reg_2973}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_0_val = {{add_ln30_reg_2653}, {6'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_10_val = {{add_ln40_reg_2703}, {7'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_11_val = {{add_ln41_reg_2708}, {6'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_12_val = {{add_ln42_reg_2713}, {6'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_13_val = {{add_ln43_reg_2718}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_14_val = {{add_ln44_reg_2723}, {3'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_15_val = {{add_ln45_reg_2728}, {6'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_1_val = {{add_ln31_reg_2658}, {6'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_2_val = {{add_ln32_reg_2663}, {4'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_3_val = {{add_ln33_reg_2668}, {4'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_4_val = {{add_ln34_reg_2673}, {4'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_5_val = {{add_ln35_reg_2678}, {6'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_6_val = {{add_ln36_reg_2683}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_7_val = {{add_ln37_reg_2688}, {7'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_8_val = {{add_ln38_reg_2693}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_s_fu_303_data_9_val = {{add_ln39_reg_2698}, {6'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_0_val = {{tmp_reg_2733}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_16_val = {{tmp_7_reg_2768}, {7'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_17_val = {{tmp_8_reg_2773}, {7'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_1_val = {{tmp_1_reg_2738}, {6'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_20_val = {{tmp_9_reg_2778}, {7'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_25_val = {{tmp_s_reg_2783}, {7'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_29_val = {{tmp_10_reg_2788}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_30_val = {{tmp_11_reg_2793}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_31_val = {{tmp_12_reg_2798}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_35_val = {{tmp_13_reg_2803}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_36_val = {{tmp_14_reg_2808}, {7'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_46_val = {{tmp_15_reg_2813}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_47_val = {{tmp_16_reg_2818}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_48_val = {{tmp_17_reg_2823}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_49_val = {{tmp_18_reg_2828}, {5'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_4_val = {{tmp_2_reg_2743}, {6'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_51_val = {{tmp_19_reg_2833}, {7'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_52_val = {{tmp_20_reg_2838}, {7'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_54_val = {{tmp_21_reg_2843}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_55_val = {{tmp_22_reg_2848}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_56_val = {{tmp_23_reg_2853}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_58_val = {{tmp_24_reg_2858}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_59_val = {{tmp_25_reg_2863}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_5_val = {{tmp_3_reg_2748}, {8'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_60_val = {{tmp_26_reg_2868}, {10'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_7_val = {{tmp_4_reg_2753}, {9'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_8_val = {{tmp_5_reg_2758}, {5'd0}};

assign grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s_fu_355_data_9_val = {{tmp_6_reg_2763}, {6'd0}};

assign layer20_out_0 = $signed(shl_ln_fu_2548_p3);

assign layer20_out_1 = $signed(shl_ln1_fu_2571_p3);

assign layer20_out_2 = $signed(shl_ln2_fu_2594_p3);

assign layer20_out_3 = $signed(shl_ln3_fu_2617_p3);

assign layer20_out_4 = $signed(shl_ln4_fu_2640_p3);

assign shl_ln1_fu_2571_p3 = {{tmp_55_fu_2561_p4}, {4'd0}};

assign shl_ln2_fu_2594_p3 = {{tmp_56_fu_2584_p4}, {5'd0}};

assign shl_ln3_fu_2617_p3 = {{tmp_57_fu_2607_p4}, {4'd0}};

assign shl_ln4_fu_2640_p3 = {{tmp_58_fu_2630_p4}, {5'd0}};

assign shl_ln_fu_2548_p3 = {{tmp_54_fu_2538_p4}, {5'd0}};

assign tmp_54_fu_2538_p4 = {{grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_0[14:5]}};

assign tmp_55_fu_2561_p4 = {{grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_1[14:4]}};

assign tmp_56_fu_2584_p4 = {{grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_2[14:5]}};

assign tmp_57_fu_2607_p4 = {{grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_3[14:4]}};

assign tmp_58_fu_2630_p4 = {{grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config18_s_fu_440_ap_return_4[14:5]}};

assign tmp_60_fu_467_p3 = input_1_in_sig[32'd5];

assign tmp_61_fu_495_p3 = input_1_in_sig[256'd21];

assign tmp_62_fu_523_p3 = input_1_in_sig[256'd35];

assign tmp_63_fu_551_p3 = input_1_in_sig[256'd51];

assign tmp_64_fu_579_p3 = input_1_in_sig[256'd67];

assign tmp_65_fu_607_p3 = input_1_in_sig[256'd85];

assign tmp_66_fu_635_p3 = input_1_in_sig[256'd104];

assign tmp_67_fu_663_p3 = input_1_in_sig[256'd118];

assign tmp_68_fu_691_p3 = input_1_in_sig[256'd136];

assign tmp_69_fu_719_p3 = input_1_in_sig[256'd149];

assign tmp_70_fu_747_p3 = input_1_in_sig[256'd166];

assign tmp_71_fu_775_p3 = input_1_in_sig[256'd181];

assign tmp_72_fu_803_p3 = input_1_in_sig[256'd197];

assign tmp_73_fu_831_p3 = input_1_in_sig[256'd215];

assign tmp_74_fu_859_p3 = input_1_in_sig[256'd226];

assign tmp_75_fu_887_p3 = input_1_in_sig[256'd245];

assign trunc_ln10_fu_765_p4 = {{input_1_in_sig[188:182]}};

assign trunc_ln11_fu_793_p4 = {{input_1_in_sig[204:198]}};

assign trunc_ln12_fu_821_p4 = {{input_1_in_sig[220:216]}};

assign trunc_ln13_fu_849_p4 = {{input_1_in_sig[238:227]}};

assign trunc_ln14_fu_877_p4 = {{input_1_in_sig[253:246]}};

assign trunc_ln1_fu_513_p4 = {{input_1_in_sig[45:36]}};

assign trunc_ln2_fu_541_p4 = {{input_1_in_sig[61:52]}};

assign trunc_ln30_1_fu_457_p4 = {{input_1_in_sig[13:6]}};

assign trunc_ln3_fu_569_p4 = {{input_1_in_sig[77:68]}};

assign trunc_ln4_fu_597_p4 = {{input_1_in_sig[94:86]}};

assign trunc_ln5_fu_625_p4 = {{input_1_in_sig[109:105]}};

assign trunc_ln6_fu_653_p4 = {{input_1_in_sig[125:119]}};

assign trunc_ln7_fu_681_p4 = {{input_1_in_sig[141:137]}};

assign trunc_ln8_fu_709_p4 = {{input_1_in_sig[156:150]}};

assign trunc_ln9_fu_737_p4 = {{input_1_in_sig[172:167]}};

assign trunc_ln_fu_485_p4 = {{input_1_in_sig[29:22]}};

assign zext_ln30_fu_475_p1 = tmp_60_fu_467_p3;

assign zext_ln31_fu_503_p1 = tmp_61_fu_495_p3;

assign zext_ln32_fu_531_p1 = tmp_62_fu_523_p3;

assign zext_ln33_fu_559_p1 = tmp_63_fu_551_p3;

assign zext_ln34_fu_587_p1 = tmp_64_fu_579_p3;

assign zext_ln35_fu_615_p1 = tmp_65_fu_607_p3;

assign zext_ln36_fu_643_p1 = tmp_66_fu_635_p3;

assign zext_ln37_fu_671_p1 = tmp_67_fu_663_p3;

assign zext_ln38_fu_699_p1 = tmp_68_fu_691_p3;

assign zext_ln39_fu_727_p1 = tmp_69_fu_719_p3;

assign zext_ln40_fu_755_p1 = tmp_70_fu_747_p3;

assign zext_ln41_fu_783_p1 = tmp_71_fu_775_p3;

assign zext_ln42_fu_811_p1 = tmp_72_fu_803_p3;

assign zext_ln43_fu_839_p1 = tmp_73_fu_831_p3;

assign zext_ln44_fu_867_p1 = tmp_74_fu_859_p3;

assign zext_ln45_fu_895_p1 = tmp_75_fu_887_p3;

endmodule //myproject
